"""Build questions/photos.js and images/ from reviewed photo picks.

Usage: python tools/photos/build_photos.py <path to a photo-candidates checkout>

picks.txt lists the photos a person approved after looking at them, one
specimen per line: "<specimen id> <candidate number> <candidate number> ...".
Each picked candidate is copied to images/<event>/<id>-<k>.jpg, and its credit
comes from the candidates' manifest.json.

notes.json adds a note to a photo that shows its specimen in a less typical way.
manual.json adds photos a person supplied directly (kept in tools/photos/manual/),
as {"<specimen id>": [{"file", "credit", "source"}]}.
"""
import json
import os
import shutil
import sys

from PIL import Image

MAX_SIDE = 640

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

GROUPS = {
    "rock": {"prompt": "Which rock from the official list is this?"},
    "mineral": {"prompt": "Which mineral from the official list is this?"},
    "class": {"prompt": "This arthropod belongs to which class?", "extra": ["Insecta"]},
    "order": {"prompt": "This insect belongs to which order?"},
    "tree": {"prompt": "Which tree is this? Look for clues in the leaves, bark, flowers, or seeds."},
    "plant": {"prompt": "Which plant is this?"},
    "reptile": {"prompt": "Which reptile is this?"},
    "amphibian": {"prompt": "Which amphibian is this?"},
}
ALT = {
    "rock": "Photo of a rock specimen", "mineral": "Photo of a mineral specimen",
    "class": "Photo of an arthropod", "order": "Photo of an insect",
    "tree": "Photo of part of a tree", "plant": "Photo of a plant",
    "reptile": "Photo of a reptile", "amphibian": "Photo of an amphibian",
}


def main(cand_root):
    manifest = json.load(open(os.path.join(cand_root, "candidates", "manifest.json")))
    specs = {s["id"]: s for s in json.load(open(os.path.join(HERE, "specimens.json")))["specimens"]}
    tips = json.load(open(os.path.join(HERE, "tips.json")))
    notes = json.load(open(os.path.join(HERE, "notes.json")))
    photos = []
    img_root = os.path.join(ROOT, "images")
    if os.path.isdir(img_root):
        shutil.rmtree(img_root)
    for line in open(os.path.join(HERE, "picks.txt")):
        parts = line.split()
        if not parts or parts[0].startswith("#"):
            continue
        sid, nums = parts[0], [int(n) for n in parts[1:]]
        spec = specs[sid]
        cands = manifest[sid]["candidates"]
        for k, n in enumerate(nums, 1):
            c = cands[n - 1]
            rel = "images/%s/%s-%d.jpg" % (spec["event"], sid, k)
            os.makedirs(os.path.dirname(os.path.join(ROOT, rel)), exist_ok=True)
            img = Image.open(os.path.join(cand_root, c["file"])).convert("RGB")
            img.thumbnail((MAX_SIDE, MAX_SIDE))
            img.save(os.path.join(ROOT, rel), "JPEG", quality=74, optimize=True, progressive=True)
            photos.append({
                "id": sid, "event": spec["event"], "group": spec["group"], "name": spec["name"],
                "image": rel, "credit": c["credit"], "source": c.get("source", ""),
                "alt": ALT[spec["group"]],
            })
            if notes.get(c.get("source")):
                photos[-1]["note"] = notes[c["source"]]
    manual_path = os.path.join(HERE, "manual.json")
    manual = json.load(open(manual_path)) if os.path.exists(manual_path) else {}
    for sid, items in manual.items():
        spec = specs[sid]
        start = sum(1 for p in photos if p["id"] == sid)
        for k, item in enumerate(items, start + 1):
            rel = "images/%s/%s-%d.jpg" % (spec["event"], sid, k)
            os.makedirs(os.path.dirname(os.path.join(ROOT, rel)), exist_ok=True)
            img = Image.open(os.path.join(ROOT, item["file"])).convert("RGB")
            img.thumbnail((MAX_SIDE, MAX_SIDE))
            img.save(os.path.join(ROOT, rel), "JPEG", quality=74, optimize=True, progressive=True)
            photos.append({
                "id": sid, "event": spec["event"], "group": spec["group"], "name": spec["name"],
                "image": rel, "credit": item["credit"], "source": item.get("source", ""),
                "alt": ALT[spec["group"]],
            })
            if item.get("note"):
                photos[-1]["note"] = item["note"]
    used_tips = {p["id"]: tips[p["id"]] for p in photos}
    out = {"groups": GROUPS, "tips": used_tips, "photos": photos}
    header = (
        "/* Picture ID photos. Generated by tools/photos/build_photos.py from the\n"
        " * photos approved in tools/photos/picks.txt. Each photo becomes a question in\n"
        " * its event's Picture ID section (see addPictureQuestions in app.js).\n"
        " * Photos are openly licensed; each one's credit is shown under it in the quiz.\n"
        " */\n"
    )
    with open(os.path.join(ROOT, "questions", "photos.js"), "w") as f:
        f.write(header + "window.QUIZ_PHOTOS = " + json.dumps(out, indent=1, ensure_ascii=False) + ";\n")
    by_event = {}
    for p in photos:
        by_event[p["event"]] = by_event.get(p["event"], 0) + 1
    print(len(photos), "photos", by_event)


if __name__ == "__main__":
    main(sys.argv[1])
