/* Buzzworthy (2027 NC Division A) question bank.
 * Covers the classes Arachnida, Chilopoda, Crustacea, Diplopoda, Insecta and
 * the 17 insect orders in the rules, plus body parts, life cycles, habitats,
 * ecology, and economic importance. Format notes are in geology-rocks.js.
 */
(window.QUIZ_EVENTS = window.QUIZ_EVENTS || []).push({
  id: "buzzworthy",
  name: "Buzzworthy",
  icon: "🐞",
  color: "#3e9b4f",
  blurb: "Insects and their arthropod cousins: classes, orders, body parts, life cycles, and why they matter.",
  sections: [
    {
      topic: "Arthropod classes",
      questions: [
        { q: "Insects, spiders, centipedes, millipedes, and crabs all have jointed legs and a hard outer shell. They belong to the group called...", a: "Arthropods", wrong: ["Mammals", "Reptiles", "Mollusks"], why: "'Arthropod' means 'jointed foot.'" },
        { q: "An arthropod's hard outer covering is called an...", type: "type", a: ["exoskeleton"], why: "'Exo' means outside. The exoskeleton protects the animal and holds its muscles." },
        { q: "How many legs does an adult insect have?", a: "6", wrong: ["4", "8", "Many pairs"], why: "All adult insects have 6 legs in 3 pairs, attached to the thorax." },
        { q: "What are the three body parts of an insect, from front to back?", a: "Head, thorax, abdomen", wrong: ["Head, abdomen, thorax", "Cephalothorax, abdomen, tail", "Head, body, tail"], why: "Every adult insect has these three body regions." },
        { q: "Which class do spiders, ticks, mites, and scorpions belong to?", type: "type", a: ["arachnida", "arachnids", "arachnid"], why: "Arachnids have 8 legs, 2 body parts, and no antennae." },
        { q: "How many legs does an arachnid have?", a: "8", wrong: ["6", "10", "100"], why: "Spiders, ticks, mites, and scorpions all have 8 legs." },
        { q: "Arachnids have two main body parts. What are they?", a: "Cephalothorax and abdomen", wrong: ["Head, thorax, and abdomen", "Head and tail", "Thorax and wings"], why: "The cephalothorax is the head and thorax joined together." },
        { q: "Which of these do arachnids NOT have?", a: "Antennae", wrong: ["Legs", "An exoskeleton", "An abdomen"], why: "Insects have antennae. Arachnids don't." },
        { q: "Centipedes belong to which class?", a: "Chilopoda", wrong: ["Diplopoda", "Arachnida", "Insecta"], why: "Chilopoda centipedes have one pair of legs on each body segment." },
        { q: "Millipedes belong to which class?", a: "Diplopoda", wrong: ["Chilopoda", "Crustacea", "Arachnida"], why: "'Diplo' means double. Millipedes have two pairs of legs on most body segments." },
        { q: "How can you tell a centipede from a millipede?", a: "Centipedes have 1 pair of legs per segment; millipedes have 2 pairs", wrong: ["Centipedes have 8 legs total", "Millipedes have wings", "Centipedes have no head"], why: "Centipedes are also flatter and faster. Millipedes are rounder and slower." },
        { q: "Which arthropod is a fast-moving predator with venomous claws that catches insects?", a: "Centipede", wrong: ["Millipede", "Pill bug", "Silverfish"], why: "Centipedes hunt with a pair of fang-like claws right behind their head." },
        { q: "Which arthropod moves slowly, eats decaying leaves, and often curls into a spiral when disturbed?", a: "Millipede", wrong: ["Centipede", "Spider", "Scorpion"], why: "Millipedes are decomposers. Some ooze bad-smelling chemicals to protect themselves." },
        { q: "Crabs, shrimp, crayfish, and pill bugs belong to which group?", type: "type", a: ["crustacea", "crustaceans", "crustacean"], why: "Most crustaceans live in water and breathe with gills." },
        { q: "Pill bugs (roly-polies) are not insects. What are they?", a: "Crustaceans", wrong: ["Arachnids", "Beetles", "Millipedes"], why: "Pill bugs are land crustaceans, related to shrimp and crabs. They need damp places to breathe." },
        { q: "How many pairs of antennae do most crustaceans have?", a: "2 pairs", wrong: ["None", "1 pair", "5 pairs"], why: "Crustaceans have two pairs of antennae. Insects have one pair." },
        { q: "Which of these is an insect?", a: "Ladybug", wrong: ["Spider", "Centipede", "Pill bug"], why: "Ladybugs are beetles with 6 legs and 3 body parts." },
        { q: "Which of these is NOT an insect?", a: "Tick", wrong: ["Ant", "Flea", "Silverfish"], why: "Ticks have 8 legs, so they're arachnids." },
        { q: "True or false: Spiders are insects.", a: "False", wrong: ["True"], why: "Spiders are arachnids: 8 legs, 2 body parts, and no antennae." },
        { q: "True or false: Centipedes and millipedes are insects.", a: "False", wrong: ["True"], why: "They're arthropods, but they're in the classes Chilopoda and Diplopoda, not Insecta." },
        { q: "The class that includes all insects is called...", type: "type", a: ["insecta"], why: "Class Insecta is the biggest group of animals on Earth." },
        { q: "A scientist who studies insects is called an...", type: "type", a: ["entomologist"], why: "Entomology is the study of insects." },
        { q: "Which group has the most known kinds (species) of animals on Earth?", a: "Insects", wrong: ["Mammals", "Birds", "Fish"], why: "Scientists have named about a million insect species." }
      ]
    },
    {
      topic: "Insect body parts",
      questions: [
        { q: "Which insect body part are the legs and wings attached to?", type: "type", a: ["thorax"], why: "The thorax is packed with muscles for walking and flying." },
        { q: "Which insect body part holds most of the digestive system and makes eggs?", a: "Abdomen", wrong: ["Head", "Thorax", "Antennae"], why: "The abdomen is the back section." },
        { q: "How many antennae does an insect have?", a: "2 (one pair)", wrong: ["None", "4", "6"], why: "Insects have one pair of antennae on the head." },
        { q: "What do insects mostly use their antennae for?", a: "Smelling and touching", wrong: ["Seeing", "Chewing", "Breathing"], why: "Antennae work like a nose and fingertips combined." },
        { q: "Eyes made of hundreds or thousands of tiny lenses are called...", a: "Compound eyes", wrong: ["Simple eyes", "Spiracles", "Mandibles"], why: "Compound eyes are great at spotting movement." },
        { q: "Small, simple eyes on top of many insects' heads that sense light and dark are called...", a: "Ocelli", wrong: ["Spiracles", "Cerci", "Palps"], why: "Ocelli (oh-SELL-eye) help insects tell light from dark." },
        { q: "Insects breathe through tiny holes along the sides of their bodies. What are they called?", type: "type", a: ["spiracles", "spiracle"], why: "Air enters through spiracles and moves through tubes called tracheae. Insects don't have lungs." },
        { q: "Chewing jaws that move side to side, like on a grasshopper or beetle, are called...", a: "Mandibles", wrong: ["Antennae", "Proboscis", "Cerci"], why: "Mandibles cut and crush food." },
        { q: "A butterfly's long, coiled drinking tube is called a...", type: "type", a: ["proboscis"], why: "The proboscis works like a straw for sipping nectar and coils up when not in use." },
        { q: "Which mouthpart type do mosquitoes, aphids, and stink bugs have?", a: "Piercing-sucking", wrong: ["Chewing", "Siphoning coil", "No mouthparts"], why: "They poke into plants or animals and suck out juices or blood." },
        { q: "Most adult insects have how many wings?", a: "4", wrong: ["2", "6", "8"], why: "Most have 2 pairs. Flies (Diptera) have just 1 pair." },
        { q: "The feelers at the back end of some insects, like earwig pincers or mayfly tails, are called...", a: "Cerci", wrong: ["Antennae", "Mandibles", "Ocelli"], why: "Cerci (SER-sye) are paired parts at the tip of the abdomen." },
        { q: "The egg-laying tube at the end of some female insects' abdomens is called an...", a: "Ovipositor", wrong: ["Proboscis", "Antenna", "Spiracle"], why: "'Ovi' means egg. A bee's stinger is a changed ovipositor." },
        { q: "Why do only female bees and wasps sting?", a: "The stinger is a changed egg-laying tube that only females have", wrong: ["Males are too small", "Males are asleep", "Males have stingers on their heads"], why: "The stinger evolved from the ovipositor." },
        { q: "To grow, an insect sheds its old exoskeleton. This is called...", type: "type", a: ["molting", "moulting", "molt"], why: "The exoskeleton can't stretch, so the insect crawls out and grows a new, bigger one." },
        { q: "Insect blood is called...", a: "Hemolymph", wrong: ["Plasma", "Sap", "Nectar"], why: "Hemolymph is usually clear, yellow, or greenish, not red." },
        { q: "True or false: Insects are cold-blooded, so their body temperature changes with their surroundings.", a: "True", wrong: ["False"], why: "That's why many insects bask in the sun to warm up and slow down when it's cold." }
      ]
    },
    {
      topic: "Life cycles",
      questions: [
        { q: "The change an insect goes through as it grows, like caterpillar to butterfly, is called...", type: "type", a: ["metamorphosis"], why: "Metamorphosis means 'change in form.'" },
        { q: "What are the 4 stages of complete metamorphosis, in order?", a: "Egg, larva, pupa, adult", wrong: ["Egg, nymph, adult, pupa", "Larva, egg, adult, pupa", "Egg, pupa, larva, adult"], why: "Butterflies, beetles, flies, bees, fleas, caddisflies, and lacewings grow this way." },
        { q: "What are the 3 stages of incomplete (simple) metamorphosis?", a: "Egg, nymph, adult", wrong: ["Egg, larva, pupa", "Larva, pupa, adult", "Egg, pupa, adult"], why: "Nymphs look like small adults without full wings." },
        { q: "A young grasshopper that looks like a small, wingless adult is called a...", type: "type", a: ["nymph"], why: "Nymphs molt several times as they grow and get their wings." },
        { q: "A caterpillar is which stage of a butterfly's life?", a: "Larva", wrong: ["Pupa", "Nymph", "Adult"], why: "The larva's main job is to eat and grow." },
        { q: "During which stage does a butterfly change inside a chrysalis?", a: "Pupa", wrong: ["Larva", "Egg", "Nymph"], why: "Inside the pupa, the caterpillar's body is rebuilt into a butterfly." },
        { q: "Which of these insects goes through INCOMPLETE metamorphosis?", a: "Grasshopper", wrong: ["Butterfly", "Beetle", "Honeybee"], why: "Orthoptera, Hemiptera, Odonata, Blattodea, and mayflies grow with egg, nymph, adult." },
        { q: "Which of these insects goes through COMPLETE metamorphosis?", a: "Flea", wrong: ["Cockroach", "Dragonfly", "Stink bug"], why: "Fleas go egg, larva, pupa, adult." },
        { q: "A fly's larva is called a...", type: "type", a: ["maggot"], why: "Maggots help recycle dead plants and animals." },
        { q: "A beetle's larva is often called a...", a: "Grub", wrong: ["Maggot", "Caterpillar", "Nymph"], why: "Grubs are plump, C-shaped beetle larvae." },
        { q: "Moths spin a silk case around themselves before becoming a pupa. This case is called a...", type: "type", a: ["cocoon"], why: "Moths make cocoons of silk. Butterflies form a chrysalis instead." },
        { q: "Silverfish and jumping bristletails hatch looking like tiny adults and never grow wings. This type of development is called...", a: "No metamorphosis (ametabolous)", wrong: ["Complete metamorphosis", "Incomplete metamorphosis with wings", "Pupation"], why: "These ancient wingless insects just molt and get bigger, and they keep molting even as adults." },
        { q: "Where do dragonfly and mayfly nymphs live?", a: "Underwater", wrong: ["Inside tree trunks", "In ant nests", "On other animals"], why: "They hunt or feed underwater before crawling out to become flying adults." },
        { q: "Mosquito larvae, called 'wigglers,' live...", a: "In still water", wrong: ["In dry sand", "Inside flowers", "On dogs"], why: "Dumping out standing water in buckets and tires helps control mosquitoes." },
        { q: "Some periodical cicadas stay underground as nymphs for how long before coming out all together?", a: "13 or 17 years", wrong: ["1 week", "1 month", "100 years"], why: "Periodical cicadas emerge in huge numbers every 13 or 17 years." },
        { q: "Which insects have a special extra winged stage that molts one more time before becoming a full adult?", a: "Mayflies", wrong: ["Beetles", "Fleas", "Ants"], why: "Mayflies are the only insects that molt again after getting working wings." }
      ]
    },
    {
      topic: "Insect orders",
      questions: [
        { q: "In insect order names, '-ptera' means...", a: "Wings", wrong: ["Legs", "Eyes", "Bugs"], why: "Most order names describe the wings, like Coleoptera (sheath wings) and Lepidoptera (scale wings)." },
        { q: "Beetles belong to which order?", type: "type", a: ["coleoptera"], hint: "It means 'sheath wings.'", why: "Beetles' hard front wings (elytra) cover their flying wings like a sheath." },
        { q: "A beetle's hard front wings that cover its flying wings are called...", a: "Elytra", wrong: ["Halteres", "Cerci", "Scales"], why: "Elytra lift out of the way so the thin back wings can fly." },
        { q: "Which insect order has the most species?", a: "Coleoptera (beetles)", wrong: ["Diptera (flies)", "Lepidoptera (butterflies)", "Odonata (dragonflies)"], why: "About 1 out of every 4 named animal species is a beetle!" },
        { q: "Butterflies and moths belong to which order?", type: "type", a: ["lepidoptera"], hint: "It means 'scale wings.'", why: "Their wings are covered in tiny colored scales." },
        { q: "True flies, like houseflies and mosquitoes, belong to which order?", a: "Diptera", wrong: ["Hymenoptera", "Odonata", "Trichoptera"], why: "Diptera means 'two wings.'" },
        { q: "Flies have tiny knob-shaped balancers instead of back wings. What are they called?", a: "Halteres", wrong: ["Elytra", "Cerci", "Palps"], why: "Halteres help flies stay steady in the air." },
        { q: "Ants, bees, and wasps belong to which order?", type: "type", a: ["hymenoptera"], why: "Hymenoptera means 'membrane wings.'" },
        { q: "Grasshoppers, crickets, and katydids belong to which order?", a: "Orthoptera", wrong: ["Coleoptera", "Hemiptera", "Phasmatodea"], why: "Orthoptera means 'straight wings.' They have big back legs for jumping." },
        { q: "Dragonflies and damselflies belong to which order?", type: "type", a: ["odonata"], why: "Odonata means 'toothed ones,' named for their strong jaws." },
        { q: "Stink bugs, cicadas, and aphids belong to the order of 'true bugs.' What is it called?", a: "Hemiptera", wrong: ["Coleoptera", "Diptera", "Dermaptera"], why: "Hemiptera means 'half wing.' Many true bugs have front wings that are half hard and half clear." },
        { q: "Cockroaches and termites belong to which order?", a: "Blattodea", wrong: ["Orthoptera", "Hymenoptera", "Zygentoma"], why: "Termites look like ants, but they're actually closely related to cockroaches." },
        { q: "Earwigs, with pincers on the end of their abdomen, belong to which order?", a: "Dermaptera", wrong: ["Diptera", "Hemiptera", "Neuroptera"], why: "Dermaptera means 'skin wings.' Their pincers are cerci." },
        { q: "True or false: Earwigs crawl into people's ears.", a: "False", wrong: ["True"], why: "That's an old myth. Earwigs hide in damp, dark places like under rocks and mulch." },
        { q: "Mayflies belong to which order?", a: "Ephemeroptera", wrong: ["Diptera", "Trichoptera", "Odonata"], why: "'Ephemero' means short-lived. Many adult mayflies live only a day or two." },
        { q: "Adult mayflies can't eat. About how long do many of them live as adults?", a: "About 1 or 2 days", wrong: ["About 5 years", "About 1 month", "Their whole lives are 1 hour long, including the nymph stage"], why: "Adult mayflies just mate and lay eggs. Their nymphs live underwater much longer." },
        { q: "Lacewings and antlions belong to which order?", a: "Neuroptera", wrong: ["Odonata", "Lepidoptera", "Psocodea"], why: "Neuroptera means 'nerve wings,' for their lacy, net-veined wings." },
        { q: "Stick insects belong to which order?", a: "Phasmatodea", wrong: ["Orthoptera", "Coleoptera", "Zygentoma"], why: "'Phasma' means ghost or phantom, because they're so hard to see." },
        { q: "Lice and barklice belong to which order?", a: "Psocodea", wrong: ["Siphonaptera", "Diptera", "Hemiptera"], why: "Head lice are wingless parasites. Barklice are harmless and live on tree bark." },
        { q: "Fleas belong to which order?", type: "type", a: ["siphonaptera"], why: "Siphonaptera means 'tube, without wings': a sucking mouth and no wings." },
        { q: "Caddisflies belong to which order?", a: "Trichoptera", wrong: ["Ephemeroptera", "Diptera", "Lepidoptera"], why: "Trichoptera means 'hairy wings.'" },
        { q: "Silverfish belong to which order?", a: "Zygentoma", wrong: ["Archaeognatha", "Psocodea", "Blattodea"], why: "Silverfish are wingless, silvery, and have three tail filaments." },
        { q: "Jumping bristletails belong to which order?", a: "Archaeognatha", wrong: ["Zygentoma", "Orthoptera", "Siphonaptera"], why: "'Archaeo' means ancient. These wingless insects are among the oldest insect groups." },
        { q: "Which TWO orders on the list have wingless insects with three long tails, and never grow wings?", a: "Zygentoma and Archaeognatha", wrong: ["Diptera and Odonata", "Lepidoptera and Trichoptera", "Coleoptera and Hemiptera"], why: "Silverfish (Zygentoma) and jumping bristletails (Archaeognatha)." },
        { q: "How can you tell a jumping bristletail from a silverfish?", a: "Bristletails have a humped back and big eyes that touch, and they jump", wrong: ["Bristletails have wings", "Silverfish have 8 legs", "Silverfish live only in water"], why: "Bristletails snap their abdomen to jump. Silverfish are flat and run." },
        { q: "How can you tell a damselfly from a dragonfly when it's resting?", a: "Damselflies fold their wings over their back; dragonflies hold them out flat", wrong: ["Damselflies have 6 wings", "Dragonflies are always smaller", "Damselflies have no eyes"], why: "Damselflies are also usually thinner." },
        { q: "How can you usually tell a moth from a butterfly?", a: "Moths often have feathery antennae; butterflies have thin antennae with a knob", wrong: ["Butterflies have 8 legs", "Moths have no wings", "Moths live underwater"], why: "Most moths fly at night, and most butterflies fly during the day." },
        { q: "A caddisfly adult looks a lot like a moth. How can you tell them apart?", a: "Caddisfly wings are covered in tiny hairs instead of scales", wrong: ["Caddisflies have 8 legs", "Caddisflies have no antennae", "Moths live in streams"], why: "Hairy wings are where the name Trichoptera comes from." },
        { q: "A mosquito belongs to which order?", a: "Diptera", wrong: ["Hymenoptera", "Hemiptera", "Siphonaptera"], why: "Mosquitoes are true flies with one pair of wings." },
        { q: "A ladybug belongs to which order?", a: "Coleoptera", wrong: ["Hemiptera", "Diptera", "Lepidoptera"], why: "Ladybugs (lady beetles) are beetles, with hard elytra." },
        { q: "A firefly (lightning bug) belongs to which order?", a: "Coleoptera", wrong: ["Diptera", "Hemiptera", "Odonata"], why: "Fireflies are beetles, even though we call them bugs or flies!" },
        { q: "A cicada belongs to which order?", a: "Hemiptera", wrong: ["Orthoptera", "Diptera", "Hymenoptera"], why: "Cicadas are true bugs with piercing-sucking mouthparts for drinking plant sap." },
        { q: "A termite belongs to which order?", a: "Blattodea", wrong: ["Hymenoptera", "Coleoptera", "Isoptera only"], why: "Scientists now group termites with cockroaches in Blattodea." },
        { q: "A cricket belongs to which order?", a: "Orthoptera", wrong: ["Coleoptera", "Hemiptera", "Blattodea"], why: "Crickets, like grasshoppers, have strong jumping legs." },
        { q: "A walking stick belongs to which order?", a: "Phasmatodea", wrong: ["Orthoptera", "Odonata", "Neuroptera"], why: "Stick insects are masters of camouflage." },
        { q: "A yellowjacket wasp belongs to which order?", a: "Hymenoptera", wrong: ["Diptera", "Coleoptera", "Hemiptera"], why: "Wasps, bees, and ants have a narrow 'waist' and membrane wings." },
        { q: "A head louse belongs to which order?", a: "Psocodea", wrong: ["Siphonaptera", "Hemiptera", "Zygentoma"], why: "Lice are tiny, flat, wingless insects that cling to hair or feathers." },
        { q: "Scientists only call insects from one order 'true bugs.' Which order?", a: "Hemiptera", wrong: ["Coleoptera", "Lepidoptera", "Odonata"], why: "Ladybugs and lightning bugs are actually beetles, not true bugs!" }
      ]
    },
    {
      topic: "Habitats and behavior",
      questions: [
        { q: "Caddisfly larvae live in streams and build portable cases out of...", a: "Sand, pebbles, or twigs glued with silk", wrong: ["Mud and spit only", "Leaves and honey", "Their own shed skins"], why: "The case protects the soft larva like a tiny mobile home." },
        { q: "Finding lots of mayfly, dragonfly, and caddisfly larvae in a stream usually means...", a: "The water is clean and healthy", wrong: ["The water is polluted", "The stream is about to dry up", "There are no fish"], why: "These larvae need clean, oxygen-rich water, so scientists use them as water-quality indicators." },
        { q: "Dragonfly nymphs catch prey with a special lower lip that...", a: "Shoots out fast to grab food", wrong: ["Glows in the dark", "Spins silk", "Squirts poison"], why: "Their extendable lower lip (labium) snaps out like a grabbing arm." },
        { q: "Antlion larvae, sometimes called 'doodlebugs,' catch ants by...", a: "Digging pit traps in sand", wrong: ["Spinning webs", "Chasing them in the air", "Stinging them"], why: "Ants slide down the sandy pit, and the antlion grabs them with its jaws." },
        { q: "Lacewing larvae are called 'aphid lions' because they...", a: "Eat lots of aphids", wrong: ["Roar loudly", "Have manes", "Live with lions"], why: "Gardeners like lacewings because they eat plant pests." },
        { q: "Fleas are great jumpers. Their bodies are flattened side to side, which helps them...", a: "Move easily through an animal's fur", wrong: ["Swim", "Fly faster", "Dig in sand"], why: "Their flat shape slips between hairs, and spines help them hold on." },
        { q: "Silverfish are often found in homes, where they eat...", a: "Paper, glue, and starchy foods", wrong: ["Blood", "Only live insects", "Metal"], why: "Silverfish like dark, damp places like basements and bathrooms." },
        { q: "Where do barklice usually live?", a: "On tree bark, eating algae and fungi", wrong: ["In people's hair", "Deep underwater", "Inside beehives"], why: "Unlike head lice, barklice are harmless." },
        { q: "Stick insects protect themselves mainly by...", a: "Looking like twigs (camouflage)", wrong: ["Stinging", "Glowing", "Running very fast"], why: "Some stick insects even sway like a twig in the breeze." },
        { q: "When an insect blends in with its surroundings to hide, it's using...", type: "type", a: ["camouflage"], why: "Stick insects, katydids, and many moths use camouflage." },
        { q: "A harmless hoverfly with yellow and black stripes looks like a bee. This is called...", a: "Mimicry", wrong: ["Molting", "Migration", "Hibernation"], why: "Predators avoid it because it looks like it can sting." },
        { q: "Bright colors like red, orange, and black on an insect often warn predators that it...", a: "Tastes bad or is poisonous", wrong: ["Is delicious", "Is a baby", "Is asleep"], why: "This is called warning coloration." },
        { q: "Earwig mothers are unusual among insects because they...", a: "Guard their eggs and care for their young", wrong: ["Eat their eggs right away", "Lay eggs in water", "Carry eggs on their antennae"], why: "Mother earwigs clean the eggs and protect the babies." },
        { q: "Termites can eat wood because they have...", a: "Tiny microbes in their gut that break down wood", wrong: ["Metal teeth", "Very strong stomach acid only", "Special eyes"], why: "Termites and their gut microbes help each other. That's mutualism." },
        { q: "Honeybees tell hive mates where to find flowers by doing a...", a: "Waggle dance", wrong: ["Loud song", "Color change", "Map drawn in wax"], why: "The angle and length of the dance show direction and distance." },
        { q: "Insects that live in organized colonies with different jobs, like honeybees, ants, and termites, are called...", a: "Social insects", wrong: ["Solitary insects", "Aquatic insects", "Parasites"], why: "Some members gather food, some care for young, and a queen lays eggs." },
        { q: "Ants leave invisible chemical trails for other ants to follow. These chemicals are called...", a: "Pheromones", wrong: ["Vitamins", "Minerals", "Hormones from plants"], why: "Pheromones are chemical messages insects use to communicate." },
        { q: "How do crickets usually make their chirping sound?", a: "Rubbing their wings together", wrong: ["Singing through their mouths", "Tapping their feet", "Clapping their antennae"], why: "A scraper on one wing rubs a ridged file on the other." },
        { q: "Where are a cricket's 'ears'?", a: "On its front legs", wrong: ["On its head", "On its wings", "On its antennae"], why: "Crickets and katydids hear with drum-like spots on their front legs." },
        { q: "Why do fireflies flash their lights?", a: "To find and attract mates", wrong: ["To see at night", "To warm up", "To scare the Moon"], why: "Each firefly species has its own flash pattern. Making light is called bioluminescence." },
        { q: "Which butterfly migrates thousands of miles to Mexico each fall?", a: "Monarch", wrong: ["Cabbage white", "Swallowtail", "Painted lady"], why: "Monarchs gather by the millions in mountain forests in Mexico for the winter." },
        { q: "Monarch caterpillars eat only which kind of plant?", a: "Milkweed", wrong: ["Grass", "Oak leaves", "Tomatoes"], why: "Milkweed's bitter chemicals make monarchs taste bad to birds." },
        { q: "Where do insects NOT usually live?", a: "Deep in the open ocean", wrong: ["Deserts", "Forests", "Ponds and streams"], why: "Insects live almost everywhere on land and in fresh water, but very few live in the ocean." },
        { q: "Why do moths fly around porch lights at night?", a: "Bright lights confuse the way they steer", wrong: ["They are cold", "They eat light", "They are chasing each other"], why: "Scientists think moths keep their backs toward the brightest light, which is usually the sky. A lamp tricks them." }
      ]
    },
    {
      topic: "Ecology",
      questions: [
        { q: "Moving pollen from flower to flower so plants can make seeds is called...", type: "type", a: ["pollination"], why: "Bees, butterflies, moths, flies, and beetles are all pollinators." },
        { q: "Insects that break down dead plants and animals and return nutrients to the soil are called...", a: "Decomposers", wrong: ["Pollinators", "Producers", "Predators"], why: "Termites, dung beetles, fly maggots, and millipedes are nature's recyclers." },
        { q: "Dung beetles are helpful because they...", a: "Bury animal waste, which recycles nutrients into the soil", wrong: ["Pollinate trees", "Eat mosquitoes", "Make honey"], why: "Dung beetles clean up pastures and feed the soil." },
        { q: "Insects are an important food source for...", a: "Birds, bats, frogs, lizards, and fish", wrong: ["Only other insects", "Only plants", "Nothing; nothing eats insects"], why: "Insects are a key part of many food webs." },
        { q: "A relationship where BOTH living things benefit is called...", a: "Mutualism", wrong: ["Parasitism", "Competition", "Predation"], why: "Bees get nectar and flowers get pollinated. Everyone wins!" },
        { q: "A flea living on a dog and drinking its blood is an example of...", a: "Parasitism", wrong: ["Mutualism", "Commensalism", "Pollination"], why: "The flea benefits and the dog is harmed." },
        { q: "Ants protect aphids from predators, and the aphids give the ants sweet honeydew. This is an example of...", a: "Mutualism", wrong: ["Parasitism", "Competition", "Commensalism"], why: "Both the ants and the aphids benefit." },
        { q: "A relationship where one living thing benefits and the other is not helped or harmed is called...", a: "Commensalism", wrong: ["Mutualism", "Parasitism", "Competition"], why: "For example, tiny mites sometimes ride on beetles to get to new places without harming them." },
        { q: "Close living relationships between two different kinds of organisms are called...", a: "Symbiosis", wrong: ["Metamorphosis", "Photosynthesis", "Migration"], why: "Mutualism, commensalism, and parasitism are all types of symbiosis." },
        { q: "Two kinds of caterpillars trying to eat the leaves of the same plant are an example of...", a: "Competition", wrong: ["Mutualism", "Pollination", "Decomposition"], why: "They're competing for the same food." },
        { q: "Some wasps lay their eggs inside caterpillars, and the wasp larvae eat the caterpillar from inside. The wasp is a...", a: "Parasitoid", wrong: ["Pollinator", "Decomposer", "Producer"], why: "Farmers sometimes use these tiny wasps to control crop pests." },
        { q: "Grasshoppers eat plants. That makes them...", a: "Herbivores", wrong: ["Carnivores", "Decomposers", "Producers"], why: "Herbivores eat plants." },
        { q: "Dragonflies, lacewing larvae, and centipedes hunt other animals. They are...", a: "Predators", wrong: ["Producers", "Herbivores", "Decomposers"], why: "Predators hunt and eat other animals." },
        { q: "How might a warmer climate affect insects like ticks and mosquitoes?", a: "They can spread to new places that used to be too cold", wrong: ["They will all disappear", "They will turn into spiders", "Nothing will change"], why: "Warmer winters let some insects and ticks survive farther north." },
        { q: "If warmer springs make flowers bloom earlier, but pollinators come out at their usual time, what can happen?", a: "Pollinators may miss the flowers they need", wrong: ["The flowers grow bigger", "The insects turn into birds", "Nothing at all"], why: "Climate change can put insects and plants out of sync." },
        { q: "Warmer temperatures can let some pest insects...", a: "Have more generations each year", wrong: ["Stop eating", "Grow to the size of dogs", "Stop laying eggs"], why: "Insects often develop faster in warm weather, so pest populations can grow." }
      ]
    },
    {
      topic: "Insects and people",
      questions: [
        { q: "What is North Carolina's official state insect?", a: "Honeybee", wrong: ["Firefly", "Monarch butterfly", "Ladybug"], why: "NC named the honeybee its state insect because of its importance to farming." },
        { q: "Why are bees so important to farmers?", a: "They pollinate many food crops", wrong: ["They eat weeds", "They scare away birds", "They water plants"], why: "Apples, blueberries, cucumbers, and many other crops need pollinators." },
        { q: "Which two useful products come from honeybees?", a: "Honey and beeswax", wrong: ["Silk and salt", "Milk and cotton", "Wool and paper"], why: "Beeswax is used in candles, crayons, and lip balm." },
        { q: "Silk for clothing comes from the cocoons of which insect?", a: "Silkworm moth", wrong: ["Spider", "Honeybee", "Caddisfly"], why: "Silkworms are the caterpillars of the silk moth (order Lepidoptera)." },
        { q: "A red food coloring called carmine is made from which insect?", a: "Cochineal scale insect", wrong: ["Ladybug", "Fire ant", "Red wasp"], why: "Cochineal insects (Hemiptera) are dried and crushed to make a bright red dye." },
        { q: "Shellac, a shiny coating for wood, comes from a substance made by which kind of insect?", a: "Lac insects (true bugs)", wrong: ["Butterflies", "Dragonflies", "Fleas"], why: "Lac insects are Hemiptera that ooze a resin on tree branches." },
        { q: "In many parts of the world, people eat insects like crickets and mealworms because they are high in...", a: "Protein", wrong: ["Sugar only", "Salt", "Plastic"], why: "Insects are a nutritious food that takes less land and water to raise than cattle." },
        { q: "Doctors sometimes use clean fly larvae (maggots) to help heal wounds. How?", a: "They eat away dead tissue", wrong: ["They sew the wound shut", "They make new skin", "They fight with germs using swords"], why: "Medical maggots eat only dead tissue, which helps the wound heal." },
        { q: "Which insect spreads malaria, one of the deadliest diseases in the world?", a: "Mosquito", wrong: ["Honeybee", "Ladybug", "Silverfish"], why: "Female mosquitoes pick up the malaria parasite when they bite." },
        { q: "Only female mosquitoes bite. Why do they need blood?", a: "To make their eggs", wrong: ["To fly faster", "To stay warm", "To grow wings"], why: "Blood has protein for eggs. For energy, mosquitoes drink nectar." },
        { q: "Lyme disease is spread by which arthropod?", a: "Ticks", wrong: ["Butterflies", "Millipedes", "Crickets"], why: "Ticks are arachnids. Check for ticks after playing in tall grass or woods." },
        { q: "Long ago, the Black Death (plague) was spread by which insects living on rats?", a: "Fleas", wrong: ["Bees", "Moths", "Dragonflies"], why: "Fleas carried the plague bacteria from rats to people." },
        { q: "What is the best way to prevent mosquito bites and the diseases they spread?", a: "Use insect repellent and empty standing water", wrong: ["Leave buckets of water outside", "Wear perfume", "Go out only at dusk"], why: "Mosquitoes breed in standing water and are most active around dawn and dusk." },
        { q: "Termites can be pests because they...", a: "Eat the wood in houses", wrong: ["Sting people", "Spread malaria", "Eat metal"], why: "Termites cause billions of dollars in damage to buildings each year." },
        { q: "Head lice are a nuisance because they...", a: "Live in hair and feed on tiny amounts of blood", wrong: ["Eat books", "Build nests in trees", "Pollinate flowers"], why: "Head lice spread by head-to-head contact, not by jumping." },
        { q: "Ladybugs and lacewings help gardeners because they eat...", a: "Aphids and other plant pests", wrong: ["Flowers", "Tomatoes", "Earthworms"], why: "Using living predators to control pests is called biological control." },
        { q: "Why do some farmers release helpful insects instead of spraying chemicals?", a: "To control pests without harming other wildlife", wrong: ["To make crops taste sweeter", "To make plants grow taller", "To scare away cows"], why: "This is called biological control." },
        { q: "A bug that damages crops, homes, or stored food is called a...", type: "type", a: ["pest", "pests"], why: "Most insects are harmless or helpful. Only a few are pests." },
        { q: "True or false: Most insects are harmful to people.", a: "False", wrong: ["True"], why: "Most insects are harmless or helpful, pollinating plants, recycling nutrients, and feeding other animals." }
      ]
    }
  ]
});
