/* Human Body (Anatomy & Physiology) question bank. Format notes are in rocks-minerals.js. */
(window.QUIZ_EVENTS = window.QUIZ_EVENTS || []).push({
  id: "human-body",
  name: "Human Body",
  icon: "🫀",
  color: "#d9546e",
  blurb: "Bones, muscles, heart, lungs, brain, senses, and digestion.",
  questions: [
    // --- Cells and organization ---
    { q: "What is the smallest living unit that makes up your body?", type: "type", a: ["cell", "cells"], why: "Your body is made of trillions of cells." },
    { q: "Groups of similar cells working together form a...", a: "Tissue", wrong: ["Organ", "System", "Bone"], why: "Cells make tissues, tissues make organs, and organs work together in organ systems." },
    { q: "Put these in order from smallest to largest.", a: "Cell, tissue, organ, organ system", wrong: ["Organ, cell, tissue, organ system", "Tissue, cell, organ system, organ", "Organ system, organ, tissue, cell"], why: "Cells build tissues, tissues build organs, and organs team up into systems." },
    { q: "What is the largest organ of the human body?", a: "Skin", wrong: ["Liver", "Brain", "Heart"], why: "Your skin covers your whole body. It protects you, helps control your temperature, and lets you feel touch." },
    { q: "What is the largest organ INSIDE the body?", a: "Liver", wrong: ["Heart", "Stomach", "Brain"], why: "The liver does hundreds of jobs, like cleaning your blood and making bile for digestion." },
    { q: "Keeping your body's inside conditions steady, like temperature, is called...", a: "Homeostasis", wrong: ["Metamorphosis", "Photosynthesis", "Digestion"], why: "Homeo means 'same' and stasis means 'staying.' Sweating and shivering are homeostasis in action." },
    { q: "What is normal human body temperature, about?", a: "98.6°F (37°C)", wrong: ["50°F (10°C)", "212°F (100°C)", "75°F (24°C)"], why: "Your body works hard to stay near 98.6°F. A fever means it's running warmer." },

    // --- Skeletal system ---
    { q: "About how many bones does an adult human have?", a: "206", wrong: ["106", "300", "52"], why: "Babies are born with about 300, but some fuse together as they grow." },
    { q: "Why do babies have more bones than adults?", a: "Some bones fuse together as they grow", wrong: ["Adults lose bones in accidents", "Babies have extra fingers", "Bones dissolve when you get older"], why: "For example, the skull starts as several pieces that join together." },
    { q: "What is the longest and strongest bone in the body?", a: "Femur (thigh bone)", wrong: ["Skull", "Spine", "Rib"], why: "The femur runs from your hip to your knee." },
    { q: "What is the thigh bone called?", type: "type", a: ["femur"], why: "The femur is the longest and strongest bone in your body." },
    { q: "What is the smallest bone in the body, found in the ear?", a: "Stapes (stirrup)", wrong: ["Femur", "Rib", "Kneecap"], why: "The stapes is about the size of a grain of rice." },
    { q: "Which bones protect your brain?", a: "Skull", wrong: ["Ribs", "Pelvis", "Femur"], why: "The part of the skull around the brain is called the cranium." },
    { q: "Which bones make a cage that protects your heart and lungs?", type: "type", a: ["ribs", "rib cage", "rib", "ribcage"], why: "Most people have 12 pairs of ribs." },
    { q: "The backbone is made of many small bones called...", a: "Vertebrae", wrong: ["Ribs", "Phalanges", "Tendons"], why: "Vertebrae stack up and protect your spinal cord." },
    { q: "What is your kneecap called?", a: "Patella", wrong: ["Femur", "Tibia", "Humerus"], why: "The patella protects the front of your knee joint." },
    { q: "The bones of your fingers and toes are called...", a: "Phalanges", wrong: ["Vertebrae", "Carpals", "Ribs"], why: "Each finger has 3 phalanges, except your thumb, which has 2." },
    { q: "The bone in your upper arm is called the...", a: "Humerus", wrong: ["Femur", "Tibia", "Sternum"], why: "When you hit your 'funny bone,' you're really bumping a nerve near the humerus." },
    { q: "The flat bone in the middle of your chest where many ribs connect is the...", a: "Sternum", wrong: ["Pelvis", "Scapula", "Patella"], why: "The sternum is also called the breastbone." },
    { q: "The shin bone is called the...", a: "Tibia", wrong: ["Fibula", "Femur", "Radius"], why: "The tibia is the big bone in front of your lower leg. The thinner fibula is next to it." },
    { q: "The shoulder blade is called the...", a: "Scapula", wrong: ["Clavicle", "Patella", "Sternum"], why: "Your scapula is the flat triangle-shaped bone on your upper back." },
    { q: "The collarbone is called the...", a: "Clavicle", wrong: ["Scapula", "Sternum", "Tibia"], why: "The clavicle connects your shoulder to your sternum." },
    { q: "Where bones meet, like at your knee or elbow, is called a...", type: "type", a: ["joint", "joints"], why: "Joints let your skeleton bend and move." },
    { q: "Your elbow and knee bend back and forth like a door. What kind of joint are they?", a: "Hinge joint", wrong: ["Ball-and-socket joint", "Fixed joint", "Pivot joint"], why: "Hinge joints move in one direction, like a door hinge." },
    { q: "Your shoulder and hip can swing around in circles. What kind of joint are they?", a: "Ball-and-socket joint", wrong: ["Hinge joint", "Fixed joint", "Gliding joint"], why: "A round end of one bone fits into a cup in another, so it can move in many directions." },
    { q: "Soft, spongy tissue inside some bones that makes blood cells is called bone...", type: "type", a: ["marrow"], why: "Red bone marrow makes red blood cells, white blood cells, and platelets." },
    { q: "Which mineral is most important for strong bones?", a: "Calcium", wrong: ["Sodium", "Iron", "Gold"], why: "Calcium from foods like milk, yogurt, and leafy greens helps build strong bones." },
    { q: "Bendy, rubbery tissue at the ends of bones and in your nose and ears is called...", a: "Cartilage", wrong: ["Marrow", "Enamel", "Muscle"], why: "Wiggle the tip of your nose. That's cartilage!" },
    { q: "Tough bands that connect bone to bone at a joint are called...", a: "Ligaments", wrong: ["Tendons", "Nerves", "Arteries"], why: "Ligaments hold your bones together. Tendons connect muscles to bones." },

    // --- Muscular system ---
    { q: "About how many muscles are in the human body?", a: "More than 600", wrong: ["About 50", "About 200", "Exactly 1,000"], why: "You have over 600 muscles working to move you, pump blood, and more." },
    { q: "Tough cords that connect muscles to bones are called...", type: "type", a: ["tendons", "tendon"], why: "When a muscle pulls on a tendon, the tendon pulls on the bone, and you move." },
    { q: "What is the largest tendon in the body, at the back of your ankle?", a: "Achilles tendon", wrong: ["Patella tendon", "Biceps tendon", "Jaw tendon"], why: "It's named after Achilles, a Greek hero who could only be hurt on his heel." },
    { q: "Which type of muscle is found only in the heart?", a: "Cardiac muscle", wrong: ["Skeletal muscle", "Smooth muscle", "Voluntary muscle"], why: "Cardiac muscle beats your whole life without ever getting tired." },
    { q: "Muscles you control on purpose, like in your arms and legs, are called...", a: "Skeletal muscles", wrong: ["Cardiac muscles", "Smooth muscles", "Involuntary muscles"], why: "Skeletal muscles attach to bones and are voluntary. You decide when to move them." },
    { q: "Muscles in the walls of your stomach and intestines that work automatically are called...", a: "Smooth muscles", wrong: ["Skeletal muscles", "Cardiac muscles", "Bone muscles"], why: "Smooth muscles work without you thinking about them." },
    { q: "Muscles can only do one thing to move a bone. What is it?", a: "Pull", wrong: ["Push", "Spin", "Stretch themselves"], why: "Muscles pull. That's why they work in pairs, one pulling each way." },
    { q: "When you bend your arm, which upper-arm muscle tightens?", a: "Biceps", wrong: ["Triceps", "Quadriceps", "Calf"], why: "The biceps pulls to bend your elbow. The triceps on the back pulls to straighten it." },
    { q: "When you straighten your arm, which upper-arm muscle tightens?", a: "Triceps", wrong: ["Biceps", "Hamstring", "Deltoid"], why: "Biceps and triceps are a muscle pair that pull in opposite directions." },
    { q: "What is the largest muscle in the body?", a: "Gluteus maximus", wrong: ["Biceps", "Heart", "Tongue"], why: "The gluteus maximus is your bottom muscle. It helps you stand, climb, and run." },
    { q: "The big dome-shaped muscle under your lungs that helps you breathe is the...", type: "type", a: ["diaphragm"], why: "When the diaphragm tightens and moves down, air rushes into your lungs." },

    // --- Circulatory system ---
    { q: "What organ pumps blood around your body?", type: "type", a: ["heart"], why: "Your heart beats about 100,000 times a day." },
    { q: "How many chambers does the human heart have?", a: "4", wrong: ["2", "3", "6"], why: "Two atria on top and two ventricles on the bottom." },
    { q: "The two top chambers of the heart are called...", a: "Atria", wrong: ["Ventricles", "Valves", "Arteries"], why: "The atria receive blood coming back into the heart." },
    { q: "The two bottom chambers of the heart, which pump blood out, are called...", a: "Ventricles", wrong: ["Atria", "Veins", "Capillaries"], why: "The ventricles have thick muscular walls to push blood out powerfully." },
    { q: "Blood vessels that carry blood AWAY from the heart are called...", a: "Arteries", wrong: ["Veins", "Capillaries", "Nerves"], hint: "Arteries go Away.", why: "A trick: Arteries go Away from the heart." },
    { q: "Blood vessels that carry blood BACK to the heart are called...", type: "type", a: ["veins", "vein"], why: "Veins have little valves that keep blood from flowing backward." },
    { q: "The tiniest blood vessels, where oxygen passes into your body's cells, are called...", a: "Capillaries", wrong: ["Arteries", "Veins", "Valves"], why: "Capillaries are so thin that red blood cells squeeze through in single file." },
    { q: "What is the largest artery in the body, coming right out of the heart?", a: "Aorta", wrong: ["Vena cava", "Carotid", "Femur"], why: "The aorta is about as wide as a garden hose." },
    { q: "Which blood cells carry oxygen?", a: "Red blood cells", wrong: ["White blood cells", "Platelets", "Plasma"], why: "Red blood cells contain hemoglobin, a protein that grabs onto oxygen." },
    { q: "Which blood cells fight germs and infections?", a: "White blood cells", wrong: ["Red blood cells", "Platelets", "Plasma"], why: "White blood cells are your body's defenders." },
    { q: "Which tiny cell pieces help your blood clot and stop bleeding when you get a cut?", a: "Platelets", wrong: ["Red blood cells", "White blood cells", "Neurons"], why: "Platelets clump together to plug up a cut and help form a scab." },
    { q: "The yellowish liquid part of blood is called...", type: "type", a: ["plasma"], why: "Plasma is mostly water. It carries blood cells, nutrients, and wastes." },
    { q: "The protein in red blood cells that carries oxygen and makes blood red is...", a: "Hemoglobin", wrong: ["Insulin", "Keratin", "Calcium"], why: "Hemoglobin contains iron, which is why iron is important in your diet." },
    { q: "When you count the beats of your heart at your wrist or neck, you're taking your...", type: "type", a: ["pulse", "heart rate"], why: "Each pulse is a surge of blood pushed by one heartbeat." },
    { q: "About how fast does a resting kid's heart usually beat?", a: "70 to 110 times a minute", wrong: ["5 to 10 times a minute", "300 to 400 times a minute", "Once an hour"], why: "Exercise makes your heart beat faster to deliver more oxygen." },
    { q: "Flaps inside the heart that keep blood moving in only one direction are called...", a: "Valves", wrong: ["Atria", "Capillaries", "Tendons"], why: "The 'lub-dub' sound of your heartbeat is your heart valves closing." },

    // --- Respiratory system ---
    { q: "Which organs let you breathe in oxygen and breathe out carbon dioxide?", type: "type", a: ["lungs", "lung"], why: "Your two lungs are in your chest, protected by your ribs." },
    { q: "Which gas does your body need to breathe IN?", a: "Oxygen", wrong: ["Carbon dioxide", "Helium", "Nitrogen only"], why: "Your cells use oxygen to get energy from food." },
    { q: "Which waste gas do you breathe OUT?", a: "Carbon dioxide", wrong: ["Oxygen", "Hydrogen", "Helium"], why: "Carbon dioxide is made when your cells use food for energy." },
    { q: "The tube that carries air from your throat to your lungs is the...", a: "Trachea (windpipe)", wrong: ["Esophagus", "Aorta", "Spinal cord"], why: "The trachea is stiffened by rings of cartilage so it stays open." },
    { q: "The tiny air sacs in the lungs where oxygen moves into the blood are called...", a: "Alveoli", wrong: ["Bronchi", "Villi", "Neurons"], why: "Your lungs have hundreds of millions of alveoli, each wrapped in capillaries." },
    { q: "The trachea splits into two tubes, one going to each lung. They're called...", a: "Bronchi", wrong: ["Alveoli", "Veins", "Ureters"], why: "The bronchi keep branching into smaller tubes, like the branches of a tree." },
    { q: "The flap that covers your windpipe when you swallow, so food doesn't go down the wrong way, is the...", a: "Epiglottis", wrong: ["Diaphragm", "Tonsil", "Uvula"], why: "When food 'goes down the wrong pipe,' the epiglottis didn't close in time, and you cough." },
    { q: "Your voice box, found in your throat, is called the...", a: "Larynx", wrong: ["Pharynx", "Trachea", "Liver"], why: "Vocal cords in the larynx vibrate to make sound when you talk or sing." },
    { q: "What do the tiny hairs and mucus in your nose do?", a: "Trap dust and germs", wrong: ["Help you taste", "Make oxygen", "Warm your brain"], why: "They filter the air you breathe so your lungs stay clean." },

    // --- Digestive system ---
    { q: "Where does digestion begin?", a: "In the mouth", wrong: ["In the stomach", "In the small intestine", "In the liver"], why: "Your teeth chew food, and saliva starts breaking down starches right away." },
    { q: "The liquid in your mouth that starts breaking down food is called...", type: "type", a: ["saliva", "spit"], why: "You make about a liter of saliva every day, enough to fill a big water bottle." },
    { q: "The tube that carries food from your mouth to your stomach is the...", a: "Esophagus", wrong: ["Trachea", "Small intestine", "Aorta"], why: "Muscles in the esophagus squeeze food down in waves, even if you're upside down!" },
    { q: "The wave-like muscle squeezes that push food through your digestive tract are called...", a: "Peristalsis", wrong: ["Respiration", "Circulation", "Photosynthesis"], why: "Peristalsis is like squeezing toothpaste through a tube." },
    { q: "Which organ uses strong acid and churning muscles to mash up food?", type: "type", a: ["stomach"], why: "Stomach acid is strong enough to help kill many germs in food." },
    { q: "Where are most nutrients absorbed into your blood?", a: "Small intestine", wrong: ["Stomach", "Large intestine", "Esophagus"], why: "The small intestine is about 20 feet long and lined with tiny finger-like villi." },
    { q: "The tiny finger-like bumps lining the small intestine that absorb nutrients are called...", a: "Villi", wrong: ["Alveoli", "Cilia", "Taste buds"], why: "Villi give the small intestine a huge surface area for absorbing food." },
    { q: "What is the main job of the large intestine?", a: "Absorbing water", wrong: ["Chewing food", "Making blood", "Pumping air"], why: "The large intestine soaks up water and forms solid waste." },
    { q: "Which is longer: the small intestine or the large intestine?", a: "The small intestine", wrong: ["The large intestine", "They are exactly the same", "Neither, they are both 1 inch"], why: "The small intestine is longer but narrower. 'Large' refers to how wide the large intestine is." },
    { q: "Which organ makes bile, which helps break down fats?", a: "Liver", wrong: ["Heart", "Lungs", "Kidneys"], why: "Bile is stored in the gallbladder until it's needed." },
    { q: "Which small organ stores bile until it's needed?", a: "Gallbladder", wrong: ["Pancreas", "Appendix", "Bladder"], why: "The gallbladder squeezes bile into the small intestine after you eat fatty food." },
    { q: "Which organ makes insulin to control sugar in your blood?", a: "Pancreas", wrong: ["Liver", "Stomach", "Heart"], why: "The pancreas also makes juices that help digest food." },
    { q: "Which organs clean your blood and make urine?", type: "type", a: ["kidneys", "kidney"], why: "Your two bean-shaped kidneys filter all your blood many times each day." },
    { q: "Where is urine stored until you go to the bathroom?", a: "Bladder", wrong: ["Kidney", "Stomach", "Gallbladder"], why: "The bladder is a stretchy bag that can hold about 2 cups of urine." },
    { q: "The hardest substance in the human body is...", a: "Tooth enamel", wrong: ["Bone", "Fingernails", "Cartilage"], why: "Enamel covers your teeth. Brushing helps protect it from cavities." },
    { q: "Which teeth are flat and wide, great for grinding food?", a: "Molars", wrong: ["Incisors", "Canines", "Fangs"], why: "Incisors cut, canines tear, and molars grind." },
    { q: "Which front teeth are thin and sharp for biting and cutting?", a: "Incisors", wrong: ["Molars", "Canines", "Wisdom teeth"], why: "Incisors are the teeth you use to bite into an apple." },

    // --- Nervous system and senses ---
    { q: "Which organ is the control center of your body?", type: "type", a: ["brain"], why: "Your brain controls your thoughts, feelings, movements, and senses." },
    { q: "What connects your brain to the rest of your body, running down inside your backbone?", a: "Spinal cord", wrong: ["Esophagus", "Aorta", "Trachea"], why: "The brain and spinal cord together make up the central nervous system." },
    { q: "Nerve cells that carry messages around your body are called...", a: "Neurons", wrong: ["Red blood cells", "Platelets", "Alveoli"], why: "Neurons send electrical and chemical signals very fast." },
    { q: "Which is the biggest part of the brain, used for thinking, memory, and senses?", a: "Cerebrum", wrong: ["Cerebellum", "Brain stem", "Spinal cord"], why: "The cerebrum is the wrinkly top part of the brain." },
    { q: "Which part of the brain helps you keep your balance and coordinate movement?", a: "Cerebellum", wrong: ["Cerebrum", "Brain stem", "Pituitary gland"], why: "The cerebellum means 'little brain.' It helps you ride a bike without falling." },
    { q: "Which part of the brain controls breathing and heartbeat automatically?", a: "Brain stem", wrong: ["Cerebrum", "Cerebellum", "Skull"], why: "The brain stem connects the brain to the spinal cord and runs your automatic body functions." },
    { q: "Pulling your hand away from a hot stove before you even think about it is called a...", type: "type", a: ["reflex", "reflexes"], why: "Reflexes are super fast because the signal goes through your spinal cord, not all the way up to your brain first." },
    { q: "How many main senses do people usually talk about?", a: "5", wrong: ["3", "7", "10"], why: "Sight, hearing, smell, taste, and touch. Scientists say we actually have even more, like balance!" },
    { q: "The colored part of your eye is called the...", a: "Iris", wrong: ["Pupil", "Retina", "Lens"], why: "Your iris makes the pupil bigger or smaller to control how much light gets in." },
    { q: "The black opening in the center of your eye that lets light in is the...", type: "type", a: ["pupil"], why: "Your pupils get bigger in the dark to let in more light." },
    { q: "The layer at the back of your eye that senses light is the...", a: "Retina", wrong: ["Iris", "Cornea", "Eardrum"], why: "The retina has rods for dim light and cones for color." },
    { q: "Cells in the retina that let you see colors are called...", a: "Cones", wrong: ["Rods", "Villi", "Neurons in your nose"], why: "Cones see color in bright light. Rods help you see in dim light." },
    { q: "Which part of the ear vibrates when sound waves hit it?", a: "Eardrum", wrong: ["Cochlea", "Earlobe", "Retina"], why: "The eardrum passes vibrations to three tiny bones: the hammer, anvil, and stirrup." },
    { q: "The snail-shaped part of the inner ear that turns vibrations into nerve signals is the...", a: "Cochlea", wrong: ["Eardrum", "Retina", "Larynx"], why: "Cochlea comes from the Greek word for snail." },
    { q: "Your tongue is covered with little sensors called...", type: "type", a: ["taste buds", "tastebuds", "taste bud"], why: "You have thousands of taste buds that sense sweet, salty, sour, bitter, and savory (umami)." },
    { q: "Which of these is one of the basic tastes your tongue can sense?", a: "Umami (savory)", wrong: ["Spicy", "Minty", "Cold"], why: "The 5 basic tastes are sweet, salty, sour, bitter, and umami. Spicy is actually a pain signal!" },
    { q: "Why does food taste bland when you have a stuffy nose?", a: "Smell is a big part of flavor", wrong: ["Your tongue falls asleep", "Colds remove taste buds", "Food changes when you're sick"], why: "Your nose and tongue work together to make flavor." },

    // --- Immune, endocrine, and healthy habits ---
    { q: "Which body system fights germs and keeps you from getting sick?", a: "Immune system", wrong: ["Skeletal system", "Digestive system", "Muscular system"], why: "White blood cells, your skin, and other defenders all help fight infections." },
    { q: "Chemical messengers made by glands that travel in your blood are called...", a: "Hormones", wrong: ["Neurons", "Enzymes in saliva only", "Vitamins"], why: "Hormones control growth, energy, sleep, and much more. They're part of the endocrine system." },
    { q: "What is the best way to stop spreading germs?", a: "Washing your hands with soap", wrong: ["Blowing on your hands", "Wearing a hat", "Eating candy"], why: "Scrub for about 20 seconds, as long as it takes to hum 'Happy Birthday' twice." },
    { q: "Vaccines help your body by...", a: "Teaching your immune system to recognize a germ", wrong: ["Making your bones grow", "Giving you extra blood", "Cleaning your teeth"], why: "Vaccines let your immune system practice, so it's ready if the real germ shows up." },
    { q: "What do you call a medicine that kills bacteria but doesn't work on viruses?", a: "Antibiotic", wrong: ["Vaccine", "Vitamin", "Bandage"], why: "Antibiotics like penicillin fight bacteria. Colds are usually caused by viruses, so antibiotics don't help them." },
    { q: "Which scientist discovered penicillin, the first antibiotic, in 1928?", a: "Alexander Fleming", wrong: ["Isaac Newton", "Marie Curie", "Albert Einstein"], why: "Fleming noticed that a mold had killed the bacteria growing in one of his dishes." }
  ]
});
