/* Insects (Entomology) question bank. Format notes are in rocks-minerals.js. */
(window.QUIZ_EVENTS = window.QUIZ_EVENTS || []).push({
  id: "insects",
  name: "Insects",
  icon: "🐞",
  color: "#3e9b4f",
  blurb: "Insect bodies, life cycles, insect orders, and amazing bug behavior.",
  questions: [
    // --- Insect body basics ---
    { q: "How many legs does an adult insect have?", a: "6", wrong: ["4", "8", "10"], why: "All adult insects have 6 legs, in 3 pairs." },
    { q: "How many main body parts does an insect have?", a: "3", wrong: ["2", "4", "8"], why: "Head, thorax, and abdomen." },
    { q: "What are the three body parts of an insect, from front to back?", a: "Head, thorax, abdomen", wrong: ["Head, abdomen, thorax", "Thorax, head, abdomen", "Head, body, tail"], why: "The head senses, the thorax moves, and the abdomen digests and makes eggs." },
    { q: "Which body part are an insect's legs and wings attached to?", type: "type", a: ["thorax"], why: "The thorax is the middle section. It's packed with muscles for walking and flying." },
    { q: "Which insect body part holds the stomach and makes eggs?", a: "Abdomen", wrong: ["Head", "Thorax", "Antennae"], why: "The abdomen is the back section. It holds most of the digestive system and reproductive organs." },
    { q: "How many antennae does an insect have?", a: "2", wrong: ["1", "4", "6"], why: "Insects have one pair of antennae on their heads." },
    { q: "What do insects mostly use their antennae for?", a: "Smelling and feeling", wrong: ["Seeing", "Eating", "Breathing"], why: "Antennae are like a nose and fingertips combined. Some insects use them to hear too." },
    { q: "An insect's hard outer shell, which acts like a skeleton on the outside, is called an...", type: "type", a: ["exoskeleton"], why: "'Exo' means outside. The exoskeleton protects the insect and holds its muscles." },
    { q: "To grow bigger, an insect has to shed its old exoskeleton. This is called...", a: "Molting", wrong: ["Hibernating", "Pollinating", "Swarming"], why: "The exoskeleton can't stretch, so the insect crawls out of it and grows a new, bigger one." },
    { q: "Eyes made of hundreds or thousands of tiny lenses are called...", a: "Compound eyes", wrong: ["Simple eyes", "Antennae", "Spiracles"], why: "Compound eyes are great at spotting movement. A dragonfly's eyes have tens of thousands of lenses." },
    { q: "Small, simple eyes on top of an insect's head that sense light are called...", a: "Ocelli", wrong: ["Spiracles", "Mandibles", "Palps"], why: "Ocelli (oh-SELL-eye) help insects tell light from dark." },
    { q: "Insects breathe through little holes on their sides. What are those holes called?", type: "type", a: ["spiracles", "spiracle"], why: "Insects don't have lungs. Air enters through spiracles and moves through tiny tubes." },
    { q: "Chewing jaws that move side to side, like on a grasshopper or beetle, are called...", a: "Mandibles", wrong: ["Antennae", "Proboscis", "Cerci"], why: "Mandibles cut and crush food. Ants use them to carry things too." },
    { q: "A butterfly's long, coiled drinking tube is called a...", type: "type", a: ["proboscis"], why: "A proboscis works like a straw for sipping nectar. It coils up when not in use." },
    { q: "Insects are part of a big group of animals with jointed legs and exoskeletons. This group is called...", a: "Arthropods", wrong: ["Mammals", "Reptiles", "Mollusks"], why: "Arthropods include insects, spiders, crabs, and centipedes. 'Arthropod' means 'jointed foot.'" },
    { q: "Insects are invertebrates. What does that mean?", a: "They don't have a backbone", wrong: ["They can't fly", "They live in water", "They have no legs"], why: "Invertebrates have no backbone. Most animals on Earth are invertebrates!" },
    { q: "Is a spider an insect?", a: "No, it has 8 legs and 2 body parts", wrong: ["Yes, it has 6 legs", "Yes, it has wings", "No, it has 10 legs"], why: "Spiders are arachnids. They have 8 legs, 2 body sections, and no antennae." },
    { q: "Spiders, scorpions, and ticks belong to a group with 8 legs called...", type: "type", a: ["arachnids", "arachnid", "arachnida"], why: "Arachnids have 8 legs and 2 body parts. Insects have 6 legs and 3 body parts." },
    { q: "Which of these is an insect?", a: "Ladybug", wrong: ["Spider", "Centipede", "Pill bug"], why: "Ladybugs are beetles with 6 legs and 3 body parts. The others are different kinds of arthropods." },
    { q: "Which of these is NOT an insect?", a: "Tick", wrong: ["Ant", "Bee", "Grasshopper"], why: "Ticks have 8 legs, so they're arachnids." },
    { q: "True or false: Centipedes are insects.", a: "False", wrong: ["True"], why: "Centipedes have many body segments with one pair of legs on each. They're arthropods but not insects." },
    { q: "Most adult insects have how many wings?", a: "4", wrong: ["2", "6", "8"], why: "Most have 2 pairs. Flies are special because they have just 2 wings." },
    { q: "A scientist who studies insects is called an...", type: "type", a: ["entomologist"], why: "Entomology is the study of insects." },
    { q: "Which group has the most known kinds (species) of animals on Earth?", a: "Insects", wrong: ["Mammals", "Birds", "Fish"], why: "Scientists have named about a million insect species, more than all other animals combined." },
    { q: "Insects are cold-blooded. That means...", a: "Their body temperature changes with their surroundings", wrong: ["They are always cold", "They live only in snow", "They have blue blood"], why: "That's why many insects slow down in cold weather and bask in the sun to warm up." },
    { q: "The feelers at the back end of some insects, like earwigs and mayflies, are called...", a: "Cerci", wrong: ["Antennae", "Mandibles", "Ocelli"], why: "Cerci (SER-sye) sense touch. Earwig cerci look like pincers." },
    { q: "Insect blood is called hemolymph. What color is it usually?", a: "Clear, yellow, or greenish", wrong: ["Bright red", "Deep blue", "Black"], why: "Insect blood doesn't carry oxygen the way ours does, so it doesn't need red hemoglobin." },

    // --- Metamorphosis ---
    { q: "The change an insect goes through as it grows, like caterpillar to butterfly, is called...", type: "type", a: ["metamorphosis"], why: "Metamorphosis means 'change in form.'" },
    { q: "What are the 4 stages of complete metamorphosis, in order?", a: "Egg, larva, pupa, adult", wrong: ["Egg, nymph, adult, pupa", "Larva, egg, adult, pupa", "Egg, pupa, larva, adult"], why: "A butterfly goes egg, caterpillar (larva), chrysalis (pupa), then butterfly." },
    { q: "What are the 3 stages of incomplete (simple) metamorphosis?", a: "Egg, nymph, adult", wrong: ["Egg, larva, pupa", "Larva, pupa, adult", "Egg, pupa, adult"], why: "Nymphs look like small adults without full wings. Grasshoppers grow this way." },
    { q: "A caterpillar is the ___ stage of a butterfly.", a: "Larva", wrong: ["Pupa", "Nymph", "Adult"], why: "The larva's main job is to eat and grow." },
    { q: "A butterfly's chrysalis is the ___ stage.", a: "Pupa", wrong: ["Larva", "Egg", "Nymph"], why: "Inside the pupa, the caterpillar's body is rebuilt into a butterfly." },
    { q: "The young of a grasshopper, which looks like a small wingless adult, is called a...", type: "type", a: ["nymph"], why: "Nymphs molt several times, getting bigger and growing wings." },
    { q: "Which insect goes through INCOMPLETE metamorphosis?", a: "Grasshopper", wrong: ["Butterfly", "Beetle", "Bee"], why: "Grasshoppers hatch as nymphs. Butterflies, beetles, and bees have a pupa stage." },
    { q: "Which insect goes through COMPLETE metamorphosis?", a: "Beetle", wrong: ["Grasshopper", "Dragonfly", "Cockroach"], why: "Beetles go egg, larva (grub), pupa, adult." },
    { q: "A fly's larva is called a...", a: "Maggot", wrong: ["Caterpillar", "Grub", "Nymph"], why: "Maggots are fly larvae. They help recycle dead plants and animals." },
    { q: "A beetle's larva is often called a...", a: "Grub", wrong: ["Maggot", "Caterpillar", "Nymph"], why: "Grubs are plump, C-shaped beetle larvae that often live in soil or wood." },
    { q: "Moth caterpillars spin a silk case around themselves to become a pupa. This case is called a...", type: "type", a: ["cocoon"], why: "Moths make cocoons of silk. Butterflies form a chrysalis instead." },
    { q: "Dragonfly nymphs live...", a: "Underwater", wrong: ["Inside trees", "In the clouds", "In ant nests"], why: "Dragonfly nymphs hunt underwater for months or years before climbing out to become flying adults." },

    // --- Insect orders ---
    { q: "Beetles belong to the order Coleoptera. What does Coleoptera mean?", a: "Sheath wings", wrong: ["Scale wings", "Half wings", "Two wings"], why: "Beetles' hard front wings (elytra) cover and protect the soft back wings like a sheath." },
    { q: "A beetle's hard front wings that cover its flying wings are called...", a: "Elytra", wrong: ["Halteres", "Spiracles", "Cerci"], why: "Elytra lift up out of the way so the thin back wings can fly." },
    { q: "Which insect order has the most species?", a: "Beetles (Coleoptera)", wrong: ["Flies (Diptera)", "Butterflies (Lepidoptera)", "Ants and bees (Hymenoptera)"], why: "Roughly 1 out of every 4 named animal species is a beetle!" },
    { q: "Butterflies and moths belong to the order Lepidoptera. What does that name mean?", a: "Scale wings", wrong: ["Sheath wings", "Straight wings", "Two wings"], why: "Their wings are covered in tiny scales, like dust, that make their colors." },
    { q: "Butterflies and moths are in which insect order?", type: "type", a: ["lepidoptera"], hint: "It means 'scale wings.'", why: "Lepido means scale and ptera means wings." },
    { q: "True flies, like houseflies and mosquitoes, belong to the order Diptera. What does Diptera mean?", a: "Two wings", wrong: ["Four wings", "No wings", "Hard wings"], why: "Flies have only 2 wings. Their back wings became tiny balancers called halteres." },
    { q: "Flies have tiny knob-shaped parts instead of back wings that help them balance. These are called...", a: "Halteres", wrong: ["Elytra", "Antennae", "Palps"], why: "Halteres spin like little gyroscopes to keep flies steady in the air." },
    { q: "Ants, bees, and wasps belong to which order?", a: "Hymenoptera", wrong: ["Diptera", "Odonata", "Orthoptera"], why: "Hymenoptera means 'membrane wings.'" },
    { q: "Grasshoppers, crickets, and katydids belong to which order?", a: "Orthoptera", wrong: ["Coleoptera", "Hymenoptera", "Lepidoptera"], why: "Orthoptera means 'straight wings.' They have strong back legs for jumping." },
    { q: "Dragonflies and damselflies belong to which order?", a: "Odonata", wrong: ["Diptera", "Hemiptera", "Orthoptera"], why: "Odonata means 'toothed ones,' named for their strong jaws." },
    { q: "Stink bugs, cicadas, and aphids belong to the order Hemiptera, the 'true bugs.' How do they eat?", a: "With a sucking beak", wrong: ["With chewing jaws", "They don't eat", "By absorbing food through their skin"], why: "True bugs have a straw-like beak for sucking juices from plants or animals." },
    { q: "Scientists only call insects from one order 'true bugs.' Which order?", a: "Hemiptera", wrong: ["Coleoptera", "Lepidoptera", "Odonata"], why: "Ladybugs and lightning bugs are actually beetles, not true bugs!" },
    { q: "Praying mantises belong to which order?", a: "Mantodea", wrong: ["Odonata", "Diptera", "Lepidoptera"], why: "Mantodea insects hunt with spiky front legs held like they're praying." },
    { q: "How can you usually tell a damselfly from a dragonfly when they're resting?", a: "Damselflies fold their wings together over their back", wrong: ["Damselflies have 6 wings", "Damselflies have no eyes", "Dragonflies are always smaller"], why: "Dragonflies rest with wings spread out flat. Damselflies fold them up." },
    { q: "How can you usually tell a moth from a butterfly?", a: "Moths often have feathery antennae; butterflies have clubbed antennae", wrong: ["Butterflies have 8 legs", "Moths have no wings", "Moths only live underwater"], why: "Butterfly antennae end in little knobs. Most moths fly at night, too." },
    { q: "Termites belong to the same order as...", a: "Cockroaches", wrong: ["Ants", "Butterflies", "Flies"], why: "Termites look like ants, but they're actually related to cockroaches (order Blattodea)." },
    { q: "Which insects are known for their silvery scales and are among the oldest types of insects, never growing wings?", a: "Silverfish", wrong: ["Butterflies", "Dragonflies", "Bees"], why: "Silverfish are wingless and have been around for hundreds of millions of years." },
    { q: "In Latin insect order names, '-ptera' means...", a: "Wings", wrong: ["Legs", "Eyes", "Bugs"], why: "Coleoptera, Lepidoptera, Diptera, Hymenoptera... each name describes the wings!" },

    // --- Famous insects ---
    { q: "Which insect makes honey?", type: "type", a: ["honeybee", "honey bee", "bee", "bees", "honeybees"], why: "Honeybees turn flower nectar into honey to feed their colony through winter." },
    { q: "The only bee in a hive that lays eggs is the...", a: "Queen", wrong: ["Worker", "Drone", "Guard"], why: "The queen can lay over a thousand eggs a day in spring." },
    { q: "Most honeybees in a hive are female bees that do the work. They're called...", a: "Workers", wrong: ["Drones", "Queens", "Soldiers"], why: "Workers gather food, build comb, feed babies, and guard the hive." },
    { q: "Male honeybees are called...", a: "Drones", wrong: ["Workers", "Queens", "Nymphs"], why: "Drones don't sting, and their main job is to mate with a queen." },
    { q: "Honeybees tell each other where to find flowers by doing a...", a: "Waggle dance", wrong: ["Loud song", "Color change", "Smell map drawn on the wall"], why: "The angle and length of the dance tell other bees which direction and how far to fly." },
    { q: "Bees build six-sided wax cells to store honey. What shape is that?", a: "Hexagon", wrong: ["Square", "Triangle", "Circle"], why: "Hexagons fit together with no gaps and use the least wax." },
    { q: "Moving pollen from flower to flower so plants can make seeds is called...", type: "type", a: ["pollination"], why: "Bees, butterflies, moths, and beetles are important pollinators." },
    { q: "Which butterfly migrates thousands of miles from Canada and the US to Mexico each fall?", a: "Monarch", wrong: ["Cabbage white", "Swallowtail", "Painted lady"], why: "Monarchs gather by the millions in mountain forests in Mexico for the winter." },
    { q: "Monarch caterpillars eat only one kind of plant. Which one?", a: "Milkweed", wrong: ["Grass", "Oak leaves", "Tomatoes"], why: "Milkweed has a bitter poison that makes monarchs taste bad to birds." },
    { q: "Fireflies make light using a chemical reaction. This is called...", a: "Bioluminescence", wrong: ["Photosynthesis", "Electricity", "Fluorescence"], why: "'Bio' means life and 'luminescence' means light. Fireflies flash to find mates." },
    { q: "True or false: Fireflies are actually beetles.", a: "True", wrong: ["False"], why: "Fireflies (lightning bugs) are beetles in the order Coleoptera." },
    { q: "How do crickets usually make their chirping sound?", a: "Rubbing their wings together", wrong: ["Singing through their mouth", "Tapping their feet", "Clapping their antennae"], why: "A scraper on one wing rubs a file on the other. This is called stridulation." },
    { q: "Which insect makes one of the loudest insect sounds using drum-like parts called tymbals?", a: "Cicada", wrong: ["Ant", "Ladybug", "Moth"], why: "Some cicadas can be as loud as a lawn mower!" },
    { q: "Some periodical cicadas stay underground as nymphs for how long before coming out all at once?", a: "13 or 17 years", wrong: ["1 month", "1 week", "100 years"], why: "Periodical cicadas pop out in huge numbers every 13 or 17 years." },
    { q: "Which insect hunts with spiky front legs and can turn its head to look over its shoulder?", a: "Praying mantis", wrong: ["Ladybug", "Honeybee", "Silverfish"], why: "Mantises are ambush hunters that grab prey lightning-fast." },
    { q: "Ladybugs are helpful in gardens because they eat...", a: "Aphids", wrong: ["Flowers", "Tomatoes", "Earthworms"], why: "One ladybug can eat thousands of aphids during its life." },
    { q: "Only female mosquitoes bite. Why do they need blood?", a: "To make their eggs", wrong: ["For energy to fly", "To stay warm", "To grow wings"], why: "Blood has protein the females need for eggs. Mosquitoes mostly drink nectar for energy." },
    { q: "Where do mosquitoes lay their eggs?", a: "In or near still water", wrong: ["In tree bark", "Inside flowers", "In sand dunes"], why: "Mosquito larvae (wigglers) live in water. Dumping out standing water helps control mosquitoes." },
    { q: "Which insect eats wood and builds giant mounds in some parts of the world?", a: "Termite", wrong: ["Butterfly", "Mosquito", "Firefly"], why: "Microbes in termites' guts help them digest wood." },
    { q: "Which insect is a 'walking stick' that looks like a twig?", a: "Stick insect", wrong: ["Ladybug", "Housefly", "Honeybee"], why: "Stick insects use camouflage to hide from predators." },
    { q: "Dung beetles roll balls of...", a: "Animal poop", wrong: ["Mud for houses", "Honey", "Tree sap"], why: "Dung beetles eat dung and lay eggs in it. They're amazing recyclers!" },
    { q: "Silk for fabric comes from the cocoons of which insect?", a: "Silkworm moth", wrong: ["Spider", "Honeybee", "Ant"], why: "Silkworms (caterpillars of the silk moth) spin cocoons of one long silk thread." },
    { q: "Which fast-flying insect catches other insects in midair and has huge compound eyes?", a: "Dragonfly", wrong: ["Ladybug", "Termite", "Silverfish"], why: "Dragonflies catch almost all the prey they chase. They're some of the best hunters around." },
    { q: "Which insects live in huge colonies with a queen and build underground tunnels?", a: "Ants", wrong: ["Butterflies", "Dragonflies", "Grasshoppers"], why: "Ant colonies can have millions of ants, all working together." },
    { q: "Ants leave invisible chemical trails for other ants to follow. These chemicals are called...", a: "Pheromones", wrong: ["Vitamins", "Hormones from plants", "Minerals"], why: "Pheromones are chemical messages that help insects communicate." },
    { q: "Insects that live together in organized groups with different jobs, like bees and ants, are called...", a: "Social insects", wrong: ["Solitary insects", "Aquatic insects", "Parasites"], why: "Social insects share work: some gather food, some care for young, and one or a few lay eggs." },
    { q: "A group of locusts flying together in huge numbers is called a...", type: "type", a: ["swarm"], why: "Locust swarms can have billions of insects and eat whole fields of crops." },

    // --- Insect survival ---
    { q: "When an insect blends in with its surroundings to hide, it's using...", type: "type", a: ["camouflage"], why: "Camouflage helps insects like katydids and stick insects hide from predators." },
    { q: "Some harmless insects look like dangerous ones to scare off predators, like a fly that looks like a bee. This is called...", a: "Mimicry", wrong: ["Molting", "Migration", "Hibernation"], why: "Hoverflies have yellow and black stripes like bees, but they can't sting." },
    { q: "Bright colors like red, orange, and black on an insect often warn predators that it...", a: "Tastes bad or is poisonous", wrong: ["Is delicious", "Is a baby", "Is asleep"], why: "This is called warning coloration. Predators learn to stay away." },
    { q: "Why do some moths have big 'eye spots' on their wings?", a: "To scare away predators", wrong: ["To see better", "To keep warm", "To attract ants"], why: "Eye spots can startle a bird into thinking a bigger animal is staring at it." },
    { q: "Why are bees so important to farmers?", a: "They pollinate many crops", wrong: ["They eat weeds", "They scare birds", "They water plants"], why: "Apples, almonds, blueberries, and many other crops need pollinators." },
    { q: "Insects that eat dead plants and animals and help recycle nutrients are called...", a: "Decomposers", wrong: ["Pollinators", "Producers", "Herbivores"], why: "Dung beetles, termites, and fly larvae help break down dead things and return nutrients to the soil." },
    { q: "Grasshoppers eat plants. That makes them...", a: "Herbivores", wrong: ["Carnivores", "Decomposers", "Producers"], why: "Herbivores eat plants. Carnivores, like mantises, eat other animals." },
    { q: "Where do insects NOT live?", a: "Deep in the open ocean", wrong: ["Deserts", "Rainforests", "Ponds"], why: "Insects live almost everywhere on land and in fresh water, but very few live in the ocean." },
    { q: "About how long have insects lived on Earth?", a: "More than 400 million years", wrong: ["About 100 years", "About 10,000 years", "About 1 million years"], why: "Insects were around long before the dinosaurs. Some ancient dragonflies had wings over 2 feet wide!" },
    { q: "Why can't insects grow as big as a dog today?", a: "Their way of breathing and their exoskeleton limit their size", wrong: ["They don't eat enough", "They are too lazy", "Birds won't let them"], why: "Air moves through tiny tubes, which don't work well in a big body. A huge exoskeleton would be very heavy too." },
    { q: "What do you call the small tube some insects use to lay eggs, like the long 'tail' on a female katydid?", a: "Ovipositor", wrong: ["Proboscis", "Antenna", "Spiracle"], why: "'Ovi' means egg. A bee's stinger is actually a changed ovipositor." },
    { q: "Which insects have a stinger that is a changed egg-laying tube, so only females can sting?", a: "Bees and wasps", wrong: ["Butterflies", "Flies", "Beetles"], why: "The stinger evolved from the ovipositor, which only females have." },
    { q: "Where are a butterfly's taste sensors?", a: "On its feet", wrong: ["On its wings", "On its antennae only", "On its back"], why: "Butterflies taste with their feet, so they can tell if a leaf is good for their eggs just by landing on it." },
    { q: "Where are a cricket's 'ears'?", a: "On its front legs", wrong: ["On its head", "On its wings", "On its abdomen tip"], why: "Crickets and katydids have hearing organs on their front legs, just below the knee." },
    { q: "Some insects, like ladybugs, spend the winter in a resting state, like a long sleep. This is called...", a: "Hibernation", wrong: ["Migration", "Metamorphosis", "Pollination"], why: "Ladybugs often gather in big groups under logs or rocks to rest through the cold months." },
    { q: "Water striders can walk on top of ponds. What helps them do this?", a: "Surface tension and water-repelling hairs on their legs", wrong: ["They are lighter than air", "They swim very fast", "They float on bubbles"], why: "Water's surface acts like a thin stretchy skin, and their hairy legs don't break through it." },
    { q: "A group of insects that are all the same kind and can have babies together is called a...", a: "Species", wrong: ["Colony", "Order", "Swarm"], why: "A species is one kind of living thing. The monarch butterfly is one species." },
    { q: "Why do moths fly around porch lights at night?", a: "Bright lights confuse the way they steer", wrong: ["They are cold", "They want to eat the light", "They are chasing each other"], why: "Scientists think moths keep their backs toward the brightest light, which usually means the sky. A lamp tricks them into circling." }
  ]
});
