/* Picture ID photos. Generated by tools/photos/build_photos.py from the
 * photos approved in tools/photos/picks.txt. Each photo becomes a question in
 * its event's Picture ID section (see addPictureQuestions in app.js).
 * Photos are openly licensed; each one's credit is shown under it in the quiz.
 */
window.QUIZ_PHOTOS = {
 "groups": {
  "rock": {
   "prompt": "Which rock from the official list is this?"
  },
  "mineral": {
   "prompt": "Which mineral from the official list is this?"
  },
  "class": {
   "prompt": "This arthropod belongs to which class?",
   "extra": [
    "Insecta"
   ]
  },
  "order": {
   "prompt": "This insect belongs to which order?"
  },
  "tree": {
   "prompt": "Which tree is this? Look for clues in the leaves, bark, flowers, or seeds."
  },
  "plant": {
   "prompt": "Which plant is this?"
  },
  "reptile": {
   "prompt": "Which reptile is this?"
  },
  "amphibian": {
   "prompt": "Which amphibian is this?"
  }
 },
 "tips": {
  "basalt": "Dark gray to black, heavy, and fine-grained. You can't see separate crystals. It sometimes has small gas holes.",
  "bituminous-coal": "Black, lightweight for its size, and often layered, with shiny and dull bands. It leaves black smudges on your fingers.",
  "conglomerate": "Rounded pebbles of different sizes cemented together in a finer, sandy background, like nature's concrete.",
  "gneiss": "Light and dark minerals separated into wavy stripes or bands. Grains are coarse enough to see.",
  "limestone-fossil": "Packed with shells, shell pieces, or other fossils cemented together. It fizzes with weak acid.",
  "marble": "Sugary, sparkly crystals, often white or streaked with color. Softer than glass, and it fizzes with acid.",
  "obsidian": "Shiny black volcanic glass with smooth, curved, shell-like (conchoidal) breaks and sharp edges.",
  "phyllite": "Thin layers with a silky, satiny shine, like shiny slate. The layers are often wavy.",
  "pumice": "Very light-colored and light-weight, full of tiny holes like a sponge. It can float on water.",
  "quartzite": "Very hard, with a glassy, sugary look. It breaks through the grains, not around them, and doesn't fizz in acid.",
  "sandstone": "Gritty like sandpaper, with sand-sized grains you can see or feel. It's often tan, red, or brown.",
  "schist": "Sparkly and flaky, with lots of shiny mica flakes lined up in layers. It may have garnet 'dots.'",
  "slate": "Dark gray, dull, smooth, and splits into flat, hard sheets. It 'rings' when tapped.",
  "calcite": "Often white or clear, breaks into slanted boxes (rhombs), hardness 3, and fizzes in weak acid.",
  "copper": "Copper-red metal, often with a green or brown tarnish, in twisted, branching shapes. It's malleable.",
  "corundum": "Very hard (9), often in barrel-shaped, six-sided crystals. It can be gray, brown, red (ruby), or blue (sapphire).",
  "gold": "Bright golden-yellow metal, very heavy, and soft. It never tarnishes and leaves a gold-yellow streak.",
  "hematite": "Silver-gray and metallic, or dull reddish-brown. Its streak is always reddish-brown.",
  "olivine": "Glassy, olive-green grains or crystals, often in clumps. It's the gem peridot.",
  "copperhead": "Tan to pinkish body with dark hourglass-shaped (Hershey's Kiss) bands and a coppery head. Venomous!",
  "american-beech": "Smooth, light-gray bark (even on big trees), toothed oval leaves with straight veins, and spiky husks around beechnuts.",
  "black-gum": "Shiny, oval leaves with smooth edges that turn bright scarlet in fall, blocky bark, and small blue-black berries.",
  "callery-pear": "Clouds of white five-petaled flowers in early spring, shiny round leaves with wavy edges, and tiny brown fruits.",
  "crepe-myrtle": "Smooth, peeling, mottled bark, and big clusters of crinkly pink, purple, red, or white flowers in summer.",
  "eastern-white-pine": "Soft, thin blue-green needles in bundles of 5, and long, narrow, curved cones.",
  "hickory": "Compound leaves with 5 to 9 leaflets, round nuts in thick husks that split into 4 parts, and on shagbark hickory, bark that peels in long, shaggy strips.",
  "loblolly-pine": "Long needles (6 to 9 inches) in bundles of 3, prickly cones 3 to 5 inches long, and thick bark in reddish-brown, scaly plates.",
  "longleaf-pine": "Very long needles (up to 18 inches) in bundles of 3, big cones (6 to 10 inches), and young trees that look like grass clumps.",
  "magnolia": "Big, thick, glossy evergreen leaves, often rusty underneath, large white flowers, and cone-like fruits with red seeds.",
  "oak": "Acorns! Leaves often have lobes (rounded or pointed) and grow in clusters at the twig tips.",
  "red-maple": "Leaves with 3 to 5 pointed, toothed lobes growing in opposite pairs, red twigs and flowers, and winged 'helicopter' seeds.",
  "river-birch": "Shaggy, peeling, papery bark in pinkish-tan and cinnamon curls, and diamond-shaped, double-toothed leaves.",
  "shortleaf-pine": "Short needles (3 to 5 inches) in bundles of 2 or 3, small cones (about 2 inches), and flaky bark plates dotted with tiny holes.",
  "sweetgum": "Star-shaped leaves with five points and spiky, ball-shaped 'gumball' seed pods.",
  "english-ivy": "Evergreen vine with dark, glossy, 3- to 5-lobed leaves, climbing trees and walls with little rootlets.",
  "carolina-lily": "Nodding orange to red flowers with spots, petals that curve back, and leaves in whorls around the stem.",
  "poison-ivy": "Leaves of three! The middle leaflet has a longer stalk. It can be a vine with hairy rootlets or a small shrub. Don't touch!",
  "kudzu": "A giant vine with three big leaflets, hairy stems, and purple flower clusters, blanketing trees and poles.",
  "scuppernong": "A muscadine grape vine with round, toothed leaves and round, thick-skinned bronze-green grapes.",
  "venus-flytrap": "Small rosette of leaves ending in hinged, red-lined traps with stiff 'teeth' along the edges.",
  "american-alligator": "Huge, dark, armored reptile with a broad, rounded U-shaped snout. Found in eastern NC waters.",
  "green-anole": "Small, slender lizard that is bright green or brown, with a pointed snout. Males show a pink throat fan.",
  "five-lined-skink": "Shiny, smooth lizard with five light stripes down its back. Young ones have a bright blue tail.",
  "eastern-glass-lizard": "Looks like a legless snake, but has eyelids, ear openings, and a groove along its side.",
  "eastern-fence-lizard": "Gray-brown with rough, spiny scales and wavy dark bands. Males have blue belly patches.",
  "cottonmouth": "Thick, dark body, a wide head with a dark stripe through the eye, and a white mouth lining. Venomous!",
  "eastern-diamondback": "Large, heavy snake with dark diamonds outlined in cream, and a rattle on its tail. Venomous!",
  "black-rat-snake": "Long, shiny black snake, often with faint patterns and a white chin and throat. Great climber.",
  "dekays-brownsnake": "Small, brown snake with two rows of dark spots down its back.",
  "eastern-hognose": "Thick body, upturned pointy snout, and blotchy pattern. It may flatten its neck like a cobra.",
  "eastern-kingsnake": "Shiny black with narrow white or yellow chain-like bands.",
  "banded-water-snake": "Thick-bodied water snake with dark crossbands on a lighter body, often seen near water.",
  "eastern-garter-snake": "Three light stripes running down the body, often with a checkered pattern between them.",
  "snapping-turtle": "Big head, hooked beak, long tail with a saw-toothed ridge, and a small bottom shell.",
  "painted-turtle": "Smooth, dark shell with red and yellow markings on the edges, and yellow stripes on the head.",
  "spotted-turtle": "Small, black shell sprinkled with bright yellow polka dots.",
  "eastern-box-turtle": "High, domed shell with yellow-orange patterns. The bottom shell has a hinge so it can close up. NC state reptile!",
  "yellow-bellied-slider": "A yellow patch or stripe behind each eye and a yellow belly. Often basks on logs.",
  "american-toad": "Brown and bumpy, with dry, warty skin and big bumps (glands) behind the eyes.",
  "pine-barrens-treefrog": "Bright green with a white-edged lavender or purple stripe along each side. NC state frog!",
  "bullfrog": "Very large, green to olive frog with a big round eardrum and no ridges down its back.",
  "southern-leopard-frog": "Slim, green or brown frog with dark round spots, a pointed snout, and light ridges down its back.",
  "marbled-salamander": "Stout, black salamander with bold silvery-white or gray bands. NC state salamander!",
  "red-backed-salamander": "Small, skinny salamander, usually with a red-orange stripe down its back (some are all gray).",
  "white-spotted-slimy-salamander": "Shiny black salamander sprinkled with small white or silver spots. Very sticky slime."
 },
 "photos": [
  {
   "id": "basalt",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Basalt",
   "image": "images/geology-rocks/basalt-1.jpg",
   "credit": "Photo: Nessa Eull, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Basalt_(GeoDIL_number_-_455).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "basalt",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Basalt",
   "image": "images/geology-rocks/basalt-2.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Scoriaceous_basalt_(Holocene;_Kilauea_Volcano,_Hawaii,_USA)_1_(46338873375).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "bituminous-coal",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Bituminous coal",
   "image": "images/geology-rocks/bituminous-coal-1.jpg",
   "credit": "Photo: Nessa Eull, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Bituminous_coal_(GeoDIL_number_-_501).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "bituminous-coal",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Bituminous coal",
   "image": "images/geology-rocks/bituminous-coal-2.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Pyrite_in_cannel_coal_(Bedford_Coal,_Middle_Pennsylvanian;_Noland_Tunnel%27s_north_portal_outcrop,_Tunnel_Hill,_Coshocton_County,_Ohio,_USA)_(30551896490).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "bituminous-coal",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Bituminous coal",
   "image": "images/geology-rocks/bituminous-coal-3.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Fossil_plant_stem_in_coal_(Bedford_Coal,_Middle_Pennsylvanian;_Noland_Tunnel%27s_north_portal_outcrop,_Tunnel_Hill,_Coshocton_County,_Ohio,_USA)_(31533285300).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "conglomerate",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Conglomerate",
   "image": "images/geology-rocks/conglomerate-1.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Travertine-cemented_conglomerate_4.jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "conglomerate",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Conglomerate",
   "image": "images/geology-rocks/conglomerate-2.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Travertine-cemented_conglomerate_11.jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "conglomerate",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Conglomerate",
   "image": "images/geology-rocks/conglomerate-3.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Travertine-cemented_conglomerate_9.jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "gneiss",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Gneiss",
   "image": "images/geology-rocks/gneiss-1.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Gneiss_2_(33239757534).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "gneiss",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Gneiss",
   "image": "images/geology-rocks/gneiss-2.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Gneiss_1_(16310656713).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "gneiss",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Gneiss",
   "image": "images/geology-rocks/gneiss-3.jpg",
   "credit": "Photo: Dexter Perkins, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Metapelitic_gneiss_(GeoDIL_number_-_518).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "limestone-fossil",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Fossil limestone",
   "image": "images/geology-rocks/limestone-fossil-1.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Tentaculites_gyracanthus_in_fossiliferous_limestone_(Manlius_Limestone,_Lower_Devonian;_near_Ravena,_New_York_State,_USA)_2.jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "limestone-fossil",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Fossil limestone",
   "image": "images/geology-rocks/limestone-fossil-2.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Fossiliferous_limestone.jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "limestone-fossil",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Fossil limestone",
   "image": "images/geology-rocks/limestone-fossil-3.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Fossiliferous_limestone_(Poverty_Run_Limestone,_Lower_Pennsylvanian;_Irish_Ridge_East_roadcut,_near_Trinway,_Ohio,_USA)_3_(33108365981).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "marble",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Marble",
   "image": "images/geology-rocks/marble-1.jpg",
   "credit": "Photo: Nessa Eull, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:White_marble_(GeoDIL_number_-_507).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "marble",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Marble",
   "image": "images/geology-rocks/marble-2.jpg",
   "credit": "Photo: Nessa Eull, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:White_marble_(GeoDIL_number_-_509).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "marble",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Marble",
   "image": "images/geology-rocks/marble-3.jpg",
   "credit": "Photo: Nessa Eull, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Lee_Marble_(dolomitic)_(GeoDIL_number_-_505).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "obsidian",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Obsidian",
   "image": "images/geology-rocks/obsidian-1.jpg",
   "credit": "Photo: Robert M. Lavinsky, CC BY-SA 3.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Cristobalite-Obsidian-40049.jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "obsidian",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Obsidian",
   "image": "images/geology-rocks/obsidian-2.jpg",
   "credit": "Photo: Robert M. Lavinsky, CC BY-SA 3.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Cristobalite-Obsidian-280504.jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "obsidian",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Obsidian",
   "image": "images/geology-rocks/obsidian-3.jpg",
   "credit": "Photo: Arenamontanus, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Snowflake_obsidian_specimens.jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "phyllite",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Phyllite",
   "image": "images/geology-rocks/phyllite-1.jpg",
   "credit": "Photo: Mike Davis, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Phyllite_(GeoDIL_number_-_423).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "phyllite",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Phyllite",
   "image": "images/geology-rocks/phyllite-2.jpg",
   "credit": "Photo: Mike Davis, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Orfordville_Formation_(phyllite)_(GeoDIL_number_-_330).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "pumice",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Pumice",
   "image": "images/geology-rocks/pumice-1.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Rhyolitic_pumice_(El_Cajete_Pumice,_Upper_Pleistocene,_55-60_ka;_Rt._4_roadcut,_southern_margin_of_Valles_Caldera,_northern_New_Mexico,_USA).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "pumice",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Pumice",
   "image": "images/geology-rocks/pumice-2.jpg",
   "credit": "Photo: Joseph H. Hartman, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Pumice_(GeoDIL_number_-_50).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "quartzite",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Quartzite",
   "image": "images/geology-rocks/quartzite-1.jpg",
   "credit": "Photo: Mike Davis, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Quartzite_with_jasper_pebbles_(GeoDIL_number_-_420).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "quartzite",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Quartzite",
   "image": "images/geology-rocks/quartzite-2.jpg",
   "credit": "Photo: Nessa Eull, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Pink_quartzite_(GeoDIL_number_-_419).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "quartzite",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Quartzite",
   "image": "images/geology-rocks/quartzite-3.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Quartzite_(Archean;_Hellroaring_Plateau,_Beartooth_Mountains_Montana,_USA)_(49143602783).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "sandstone",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Sandstone",
   "image": "images/geology-rocks/sandstone-1.jpg",
   "credit": "Photo: Nessa Eull, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Coconino_Sandstone_(GeoDIL_number_-_476).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "sandstone",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Sandstone",
   "image": "images/geology-rocks/sandstone-2.jpg",
   "credit": "Photo: Nessa Eull, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Sandstone_(GeoDIL_number_-_474).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "sandstone",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Sandstone",
   "image": "images/geology-rocks/sandstone-3.jpg",
   "credit": "Photo: Darla Sondrol, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Micaceous_sandstone_(GeoDIL_number_-_468).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "schist",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Schist",
   "image": "images/geology-rocks/schist-1.jpg",
   "credit": "Photo: Raimond Spekking, CC BY-SA 4.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Almandine_in_Mica_schist._Granatkogel,_%C3%96ztal,_Austria-8869.jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "schist",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Schist",
   "image": "images/geology-rocks/schist-2.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Garnet-mica_schist_(Gassetts,_Vermont,_USA)_2.jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "schist",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Schist",
   "image": "images/geology-rocks/schist-3.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Garnet-mica_schist_(Gassetts,_Vermont,_USA)_1.jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "slate",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Slate",
   "image": "images/geology-rocks/slate-1.jpg",
   "credit": "Photo: Dexter Perkins, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Gray_slate_(GeoDIL_number_-_15).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "slate",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Slate",
   "image": "images/geology-rocks/slate-2.jpg",
   "credit": "Photo: Mike Davis, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Green_slate_(GeoDIL_number_-_422).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "slate",
   "event": "geology-rocks",
   "group": "rock",
   "name": "Slate",
   "image": "images/geology-rocks/slate-3.jpg",
   "credit": "Photo: Mike Davis, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Red_Slate_(GeoDIL_number_-_421).jpg",
   "alt": "Photo of a rock specimen"
  },
  {
   "id": "calcite",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Calcite",
   "image": "images/geology-rocks/calcite-1.jpg",
   "credit": "Photo: Raimond Spekking, CC BY-SA 4.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Calcite._Lemerva,_USA-8831.jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "calcite",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Calcite",
   "image": "images/geology-rocks/calcite-2.jpg",
   "credit": "Photo: Raimond Spekking, CC BY-SA 4.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Calcite,_Mexico-8827.jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "calcite",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Calcite",
   "image": "images/geology-rocks/calcite-3.jpg",
   "credit": "Photo: Robert M. Lavinsky, CC BY-SA 3.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Calcite-20188.jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "copper",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Copper",
   "image": "images/geology-rocks/copper-1.jpg",
   "credit": "Photo: “Jonathan Zander (Digon3)\", CC BY-SA 3.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Native_Copper_Macro_Digon3.jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "copper",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Copper",
   "image": "images/geology-rocks/copper-2.jpg",
   "credit": "Photo: Chad Knutsen, CC BY-SA 4.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Native_Copper_from_Michigan.png",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "copper",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Copper",
   "image": "images/geology-rocks/copper-3.jpg",
   "credit": "Photo: Flipin,OG, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Native_copper_mineral_specimen.jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "corundum",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Corundum",
   "image": "images/geology-rocks/corundum-1.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Corundum_6.jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "corundum",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Corundum",
   "image": "images/geology-rocks/corundum-2.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Corundum_5.jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "corundum",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Corundum",
   "image": "images/geology-rocks/corundum-3.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Corundum_(India)_2.jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "gold",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Gold",
   "image": "images/geology-rocks/gold-1.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Gold_nugget_(placer_gold)_(Pennsylvania_Mountain,_Alma_Mining_District,_Park_County,_Colorado,_USA)_3_(17062522022).jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "gold",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Gold",
   "image": "images/geology-rocks/gold-2.jpg",
   "credit": "Photo: Robert M. Lavinsky, CC BY-SA 3.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Gold-cat06b.jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "gold",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Gold",
   "image": "images/geology-rocks/gold-3.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Gold_nugget_(placer_gold)_(Bulger_Basin_Placer_Deposit,_Pennsylvania_Mountain,_Alma_Mining_District,_Park_County,_Colorado,_USA)_1_(17042810066).jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "hematite",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Hematite",
   "image": "images/geology-rocks/hematite-1.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Hematite-turgite_3.jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "hematite",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Hematite",
   "image": "images/geology-rocks/hematite-2.jpg",
   "credit": "Photo: James St. John, CC BY 2.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Hematite_(Cavradi_Gorge,_Switzerland)_4.jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "olivine",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Olivine",
   "image": "images/geology-rocks/olivine-1.jpg",
   "credit": "Photo: Nessa Eull, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Olivine_(GeoDIL_number_-_528).jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "olivine",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Olivine",
   "image": "images/geology-rocks/olivine-2.jpg",
   "credit": "Photo: Tõnis Saadre, CC BY-SA 4.0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Estonian_Museum_of_Natural_History_Specimen_No_176140_photo_(g244_g244-16_jpg).jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "olivine",
   "event": "geology-rocks",
   "group": "mineral",
   "name": "Olivine",
   "image": "images/geology-rocks/olivine-3.jpg",
   "credit": "Photo: Darla Sondrol, CC0, via Wikimedia Commons",
   "source": "https://commons.wikimedia.org/wiki/File:Olivine_(GeoDIL_number_-_2386).jpg",
   "alt": "Photo of a mineral specimen"
  },
  {
   "id": "copperhead",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Copperhead",
   "image": "images/roots-reptiles/copperhead-1.jpg",
   "credit": "Photo: Eric Johnson, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/123723288",
   "alt": "Photo of a reptile"
  },
  {
   "id": "copperhead",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Copperhead",
   "image": "images/roots-reptiles/copperhead-2.jpg",
   "credit": "Photo: jillmjordan, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/272691224",
   "alt": "Photo of a reptile"
  },
  {
   "id": "copperhead",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Copperhead",
   "image": "images/roots-reptiles/copperhead-3.jpg",
   "credit": "Photo: nicholas_massey, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/13116682",
   "alt": "Photo of a reptile"
  },
  {
   "id": "american-beech",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "American beech",
   "image": "images/roots-reptiles/american-beech-1.jpg",
   "credit": "Photo: candiceken, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/315913027",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "american-beech",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "American beech",
   "image": "images/roots-reptiles/american-beech-2.jpg",
   "credit": "Photo: chantalu2, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/310746977",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "american-beech",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "American beech",
   "image": "images/roots-reptiles/american-beech-3.jpg",
   "credit": "Photo: Milo Pyne, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/69953260",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "black-gum",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Black gum",
   "image": "images/roots-reptiles/black-gum-1.jpg",
   "credit": "Photo: Nathan Augustine, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/398609495",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "black-gum",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Black gum",
   "image": "images/roots-reptiles/black-gum-2.jpg",
   "credit": "Photo: Alan Weakley, CC0, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/67491052",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "black-gum",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Black gum",
   "image": "images/roots-reptiles/black-gum-3.jpg",
   "credit": "Photo: Kelly Applegate, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/188897292",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "callery-pear",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Bradford (Callery) pear",
   "image": "images/roots-reptiles/callery-pear-1.jpg",
   "credit": "Photo: Jared Evans, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/149737428",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "callery-pear",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Bradford (Callery) pear",
   "image": "images/roots-reptiles/callery-pear-2.jpg",
   "credit": "Photo: bonnieeamick, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/281420689",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "callery-pear",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Bradford (Callery) pear",
   "image": "images/roots-reptiles/callery-pear-3.jpg",
   "credit": "Photo: briannali12345, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/45293355",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "crepe-myrtle",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Crepe myrtle",
   "image": "images/roots-reptiles/crepe-myrtle-1.jpg",
   "credit": "Photo: frank..., CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/174542182",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "crepe-myrtle",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Crepe myrtle",
   "image": "images/roots-reptiles/crepe-myrtle-2.jpg",
   "credit": "Photo: grinnin, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/177612673",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "crepe-myrtle",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Crepe myrtle",
   "image": "images/roots-reptiles/crepe-myrtle-3.jpg",
   "credit": "Photo: bichaels, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/300311488",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "eastern-white-pine",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Eastern white pine",
   "image": "images/roots-reptiles/eastern-white-pine-1.jpg",
   "credit": "Photo: Gayle56, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/399261023",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "eastern-white-pine",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Eastern white pine",
   "image": "images/roots-reptiles/eastern-white-pine-2.jpg",
   "credit": "Photo: Rowan, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/142700021",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "eastern-white-pine",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Eastern white pine",
   "image": "images/roots-reptiles/eastern-white-pine-3.jpg",
   "credit": "Photo: The Leach, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/124447208",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "hickory",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Hickory",
   "image": "images/roots-reptiles/hickory-1.jpg",
   "credit": "Photo: Connor Cochrane, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/154348933",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "hickory",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Hickory",
   "image": "images/roots-reptiles/hickory-2.jpg",
   "credit": "Photo: R Haven Wiley, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/80322541",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "hickory",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Hickory",
   "image": "images/roots-reptiles/hickory-3.jpg",
   "credit": "Photo: caw33iii, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/12090075",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "loblolly-pine",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Loblolly pine",
   "image": "images/roots-reptiles/loblolly-pine-1.jpg",
   "credit": "Photo: hopeanne, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/64020977",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "loblolly-pine",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Loblolly pine",
   "image": "images/roots-reptiles/loblolly-pine-2.jpg",
   "credit": "Photo: Milo Pyne, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/339210198",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "loblolly-pine",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Loblolly pine",
   "image": "images/roots-reptiles/loblolly-pine-3.jpg",
   "credit": "Photo: Ashwin Srinivasan, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/5829487",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "longleaf-pine",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Longleaf pine",
   "image": "images/roots-reptiles/longleaf-pine-1.jpg",
   "credit": "Photo: North Carolina Natural Heritage Program, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/704233",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "longleaf-pine",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Longleaf pine",
   "image": "images/roots-reptiles/longleaf-pine-2.jpg",
   "credit": "Photo: Jeff Clark, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/269070370",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "longleaf-pine",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Longleaf pine",
   "image": "images/roots-reptiles/longleaf-pine-3.jpg",
   "credit": "Photo: Austin Pursley, CC0, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/66452605",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "magnolia",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Magnolia",
   "image": "images/roots-reptiles/magnolia-1.jpg",
   "credit": "Photo: riverotters, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/104379102",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "magnolia",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Magnolia",
   "image": "images/roots-reptiles/magnolia-2.jpg",
   "credit": "Photo: ftwalls, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/49031554",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "magnolia",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Magnolia",
   "image": "images/roots-reptiles/magnolia-3.jpg",
   "credit": "Photo: jhileman735, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/94502817",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "oak",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Oak",
   "image": "images/roots-reptiles/oak-1.jpg",
   "credit": "Photo: Douglas Goldman, CC BY-SA, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/60265340",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "oak",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Oak",
   "image": "images/roots-reptiles/oak-2.jpg",
   "credit": "Photo: Austin Pursley, CC0, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/42761568",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "oak",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Oak",
   "image": "images/roots-reptiles/oak-3.jpg",
   "credit": "Photo: dzy, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/330125099",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "red-maple",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Red maple",
   "image": "images/roots-reptiles/red-maple-1.jpg",
   "credit": "Photo: Annkatrin Rose, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/99165859",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "red-maple",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Red maple",
   "image": "images/roots-reptiles/red-maple-2.jpg",
   "credit": "Photo: sblumen, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/150865491",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "red-maple",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Red maple",
   "image": "images/roots-reptiles/red-maple-3.jpg",
   "credit": "Photo: Turner Brockman, CC BY-SA, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/391123931",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "river-birch",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "River birch",
   "image": "images/roots-reptiles/river-birch-1.jpg",
   "credit": "Photo: jimclark, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/91940281",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "river-birch",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "River birch",
   "image": "images/roots-reptiles/river-birch-2.jpg",
   "credit": "Photo: Ken Kneidel, CC0, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/17571115",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "river-birch",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "River birch",
   "image": "images/roots-reptiles/river-birch-3.jpg",
   "credit": "Photo: mbrenner131, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/41068165",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "shortleaf-pine",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Shortleaf pine",
   "image": "images/roots-reptiles/shortleaf-pine-1.jpg",
   "credit": "Photo: Michael J. Papay, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/176323454",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "shortleaf-pine",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Shortleaf pine",
   "image": "images/roots-reptiles/shortleaf-pine-2.jpg",
   "credit": "Photo: Scott Ward, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/144795785",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "sweetgum",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Sweetgum",
   "image": "images/roots-reptiles/sweetgum-1.jpg",
   "credit": "Photo: Steve Taylor, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/46789279",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "sweetgum",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Sweetgum",
   "image": "images/roots-reptiles/sweetgum-2.jpg",
   "credit": "Photo: jade3999, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/81323908",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "sweetgum",
   "event": "roots-reptiles",
   "group": "tree",
   "name": "Sweetgum",
   "image": "images/roots-reptiles/sweetgum-3.jpg",
   "credit": "Photo: George Pauly, CC0, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/45207540",
   "alt": "Photo of part of a tree"
  },
  {
   "id": "english-ivy",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "English ivy",
   "image": "images/roots-reptiles/english-ivy-1.jpg",
   "credit": "Photo: trevorsumlin, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/32304560",
   "alt": "Photo of a plant"
  },
  {
   "id": "english-ivy",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "English ivy",
   "image": "images/roots-reptiles/english-ivy-2.jpg",
   "credit": "Photo: mecklenburg_nc, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/335573389",
   "alt": "Photo of a plant"
  },
  {
   "id": "english-ivy",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "English ivy",
   "image": "images/roots-reptiles/english-ivy-3.jpg",
   "credit": "Photo: ellagr13, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/314402134",
   "alt": "Photo of a plant"
  },
  {
   "id": "carolina-lily",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Carolina lily",
   "image": "images/roots-reptiles/carolina-lily-1.jpg",
   "credit": "Photo: Nick Newberry, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/15137463",
   "alt": "Photo of a plant"
  },
  {
   "id": "carolina-lily",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Carolina lily",
   "image": "images/roots-reptiles/carolina-lily-2.jpg",
   "credit": "Photo: Becky Dill, CC0, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/176427630",
   "alt": "Photo of a plant"
  },
  {
   "id": "carolina-lily",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Carolina lily",
   "image": "images/roots-reptiles/carolina-lily-3.jpg",
   "credit": "Photo: rangerkatie_salmoncreek, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/387942635",
   "alt": "Photo of a plant"
  },
  {
   "id": "poison-ivy",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Eastern poison ivy",
   "image": "images/roots-reptiles/poison-ivy-1.jpg",
   "credit": "Photo: jackollis, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/210474533",
   "alt": "Photo of a plant"
  },
  {
   "id": "poison-ivy",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Eastern poison ivy",
   "image": "images/roots-reptiles/poison-ivy-2.jpg",
   "credit": "Photo: Jeff Clark, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/276848440",
   "alt": "Photo of a plant"
  },
  {
   "id": "poison-ivy",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Eastern poison ivy",
   "image": "images/roots-reptiles/poison-ivy-3.jpg",
   "credit": "Photo: Scott Ward, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/204874575",
   "alt": "Photo of a plant"
  },
  {
   "id": "kudzu",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Kudzu",
   "image": "images/roots-reptiles/kudzu-1.jpg",
   "credit": "Photo: sewing, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/64122932",
   "alt": "Photo of a plant"
  },
  {
   "id": "kudzu",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Kudzu",
   "image": "images/roots-reptiles/kudzu-2.jpg",
   "credit": "Photo: Nate Hartley, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/18018289",
   "alt": "Photo of a plant"
  },
  {
   "id": "kudzu",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Kudzu",
   "image": "images/roots-reptiles/kudzu-3.jpg",
   "credit": "Photo: Kathleen Pryer, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/7904805",
   "alt": "Photo of a plant"
  },
  {
   "id": "scuppernong",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Scuppernong grape",
   "image": "images/roots-reptiles/scuppernong-1.jpg",
   "credit": "Photo: Suzanne Cadwell, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/345476",
   "alt": "Photo of a plant"
  },
  {
   "id": "scuppernong",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Scuppernong grape",
   "image": "images/roots-reptiles/scuppernong-2.jpg",
   "credit": "Photo: Ava, CC0, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/57468365",
   "alt": "Photo of a plant"
  },
  {
   "id": "scuppernong",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Scuppernong grape",
   "image": "images/roots-reptiles/scuppernong-3.jpg",
   "credit": "Photo: dakoalabear, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/4306668",
   "alt": "Photo of a plant"
  },
  {
   "id": "venus-flytrap",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Venus flytrap",
   "image": "images/roots-reptiles/venus-flytrap-1.jpg",
   "credit": "Photo: johnmauser, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/288851983",
   "alt": "Photo of a plant"
  },
  {
   "id": "venus-flytrap",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Venus flytrap",
   "image": "images/roots-reptiles/venus-flytrap-2.jpg",
   "credit": "Photo: Erin Haase, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/1911495",
   "alt": "Photo of a plant"
  },
  {
   "id": "venus-flytrap",
   "event": "roots-reptiles",
   "group": "plant",
   "name": "Venus flytrap",
   "image": "images/roots-reptiles/venus-flytrap-3.jpg",
   "credit": "Photo: catskillbob, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/169761302",
   "alt": "Photo of a plant"
  },
  {
   "id": "american-alligator",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "American alligator",
   "image": "images/roots-reptiles/american-alligator-1.jpg",
   "credit": "Photo: dogbowlbookpile, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/237324314",
   "alt": "Photo of a reptile"
  },
  {
   "id": "american-alligator",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "American alligator",
   "image": "images/roots-reptiles/american-alligator-2.jpg",
   "credit": "Photo: al_bennett, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/8726642",
   "alt": "Photo of a reptile"
  },
  {
   "id": "american-alligator",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "American alligator",
   "image": "images/roots-reptiles/american-alligator-3.jpg",
   "credit": "Photo: Conway Hawn, CC0, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/166169637",
   "alt": "Photo of a reptile"
  },
  {
   "id": "green-anole",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Green anole",
   "image": "images/roots-reptiles/green-anole-1.jpg",
   "credit": "Photo: Mark Shields, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/157820673",
   "alt": "Photo of a reptile"
  },
  {
   "id": "green-anole",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Green anole",
   "image": "images/roots-reptiles/green-anole-2.jpg",
   "credit": "Photo: Robby Deans, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/15409625",
   "alt": "Photo of a reptile"
  },
  {
   "id": "green-anole",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Green anole",
   "image": "images/roots-reptiles/green-anole-3.jpg",
   "credit": "Photo: Catherine, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/46382823",
   "alt": "Photo of a reptile"
  },
  {
   "id": "five-lined-skink",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Southeastern five-lined skink",
   "image": "images/roots-reptiles/five-lined-skink-1.jpg",
   "credit": "Photo: Robby Deans, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/3880163",
   "alt": "Photo of a reptile"
  },
  {
   "id": "five-lined-skink",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Southeastern five-lined skink",
   "image": "images/roots-reptiles/five-lined-skink-2.jpg",
   "credit": "Photo: Todd Council, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/285494696",
   "alt": "Photo of a reptile"
  },
  {
   "id": "five-lined-skink",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Southeastern five-lined skink",
   "image": "images/roots-reptiles/five-lined-skink-3.jpg",
   "credit": "Photo: CHRONIC_TREES, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/350545230",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-glass-lizard",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern glass lizard",
   "image": "images/roots-reptiles/eastern-glass-lizard-1.jpg",
   "credit": "Photo: Kevin, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/155875505",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-glass-lizard",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern glass lizard",
   "image": "images/roots-reptiles/eastern-glass-lizard-2.jpg",
   "credit": "Photo: monoceba, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/262883253",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-glass-lizard",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern glass lizard",
   "image": "images/roots-reptiles/eastern-glass-lizard-3.jpg",
   "credit": "Photo: Tom Davis, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/318385474",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-fence-lizard",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern fence lizard",
   "image": "images/roots-reptiles/eastern-fence-lizard-1.jpg",
   "credit": "Photo: jaybird52, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/349273648",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-fence-lizard",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern fence lizard",
   "image": "images/roots-reptiles/eastern-fence-lizard-2.jpg",
   "credit": "Photo: annajohnson816, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/74772717",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-fence-lizard",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern fence lizard",
   "image": "images/roots-reptiles/eastern-fence-lizard-3.jpg",
   "credit": "Photo: Michael J. Papay, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/149932002",
   "alt": "Photo of a reptile"
  },
  {
   "id": "cottonmouth",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Cottonmouth",
   "image": "images/roots-reptiles/cottonmouth-1.jpg",
   "credit": "Photo: Max Ramey, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/119664813",
   "alt": "Photo of a reptile"
  },
  {
   "id": "cottonmouth",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Cottonmouth",
   "image": "images/roots-reptiles/cottonmouth-2.jpg",
   "credit": "Photo: Nick Spigler, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/285113541",
   "alt": "Photo of a reptile"
  },
  {
   "id": "cottonmouth",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Cottonmouth",
   "image": "images/roots-reptiles/cottonmouth-3.jpg",
   "credit": "Photo: Shreybae, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/360741859",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-diamondback",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern diamondback rattlesnake",
   "image": "images/roots-reptiles/eastern-diamondback-1.jpg",
   "credit": "Photo: Ty Sharrow, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/40086559",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-diamondback",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern diamondback rattlesnake",
   "image": "images/roots-reptiles/eastern-diamondback-2.jpg",
   "credit": "Photo: Matt Cohen and Elizabeth Hargrave, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/104966897",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-diamondback",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern diamondback rattlesnake",
   "image": "images/roots-reptiles/eastern-diamondback-3.jpg",
   "credit": "Photo: bdholt, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/88004964",
   "alt": "Photo of a reptile"
  },
  {
   "id": "black-rat-snake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Black rat snake",
   "image": "images/roots-reptiles/black-rat-snake-1.jpg",
   "credit": "Photo: Zane Fish, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/346674374",
   "alt": "Photo of a reptile"
  },
  {
   "id": "black-rat-snake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Black rat snake",
   "image": "images/roots-reptiles/black-rat-snake-2.jpg",
   "credit": "Photo: Troy, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/29826301",
   "alt": "Photo of a reptile"
  },
  {
   "id": "black-rat-snake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Black rat snake",
   "image": "images/roots-reptiles/black-rat-snake-3.jpg",
   "credit": "Photo: Samuel Cannon, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/180940026",
   "alt": "Photo of a reptile"
  },
  {
   "id": "dekays-brownsnake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Dekay's brownsnake",
   "image": "images/roots-reptiles/dekays-brownsnake-1.jpg",
   "credit": "Photo: Patrick Coin, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/349319499",
   "alt": "Photo of a reptile"
  },
  {
   "id": "dekays-brownsnake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Dekay's brownsnake",
   "image": "images/roots-reptiles/dekays-brownsnake-2.jpg",
   "credit": "Photo: Michael J. Papay, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/237149933",
   "alt": "Photo of a reptile"
  },
  {
   "id": "dekays-brownsnake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Dekay's brownsnake",
   "image": "images/roots-reptiles/dekays-brownsnake-3.jpg",
   "credit": "Photo: Becky Dill, CC0, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/109009025",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-hognose",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern hognose snake",
   "image": "images/roots-reptiles/eastern-hognose-1.jpg",
   "credit": "Photo: jefflewisnature, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/238308073",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-hognose",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern hognose snake",
   "image": "images/roots-reptiles/eastern-hognose-2.jpg",
   "credit": "Photo: Joshua Liverman, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/11187473",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-hognose",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern hognose snake",
   "image": "images/roots-reptiles/eastern-hognose-3.jpg",
   "credit": "Photo: gibbonsg1962nc, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/195995767",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-kingsnake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern kingsnake",
   "image": "images/roots-reptiles/eastern-kingsnake-1.jpg",
   "credit": "Photo: Shreybae, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/349678909",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-kingsnake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern kingsnake",
   "image": "images/roots-reptiles/eastern-kingsnake-2.jpg",
   "credit": "Photo: Matthew Lumsden, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/346711606",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-kingsnake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern kingsnake",
   "image": "images/roots-reptiles/eastern-kingsnake-3.jpg",
   "credit": "Photo: jctalkington, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/331004332",
   "alt": "Photo of a reptile"
  },
  {
   "id": "banded-water-snake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Banded water snake",
   "image": "images/roots-reptiles/banded-water-snake-1.jpg",
   "credit": "Photo: Miles Buddy, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/188783687",
   "alt": "Photo of a reptile"
  },
  {
   "id": "banded-water-snake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Banded water snake",
   "image": "images/roots-reptiles/banded-water-snake-2.jpg",
   "credit": "Photo: Benjamin Genter, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/172414501",
   "alt": "Photo of a reptile"
  },
  {
   "id": "banded-water-snake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Banded water snake",
   "image": "images/roots-reptiles/banded-water-snake-3.jpg",
   "credit": "Photo: Richard D Reams, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/221004896",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-garter-snake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern garter snake",
   "image": "images/roots-reptiles/eastern-garter-snake-1.jpg",
   "credit": "Photo: tewsc1, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/109668000",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-garter-snake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern garter snake",
   "image": "images/roots-reptiles/eastern-garter-snake-2.jpg",
   "credit": "Photo: Kevin, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/228087435",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-garter-snake",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern garter snake",
   "image": "images/roots-reptiles/eastern-garter-snake-3.jpg",
   "credit": "Photo: willissl, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/158752067",
   "alt": "Photo of a reptile"
  },
  {
   "id": "snapping-turtle",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Snapping turtle",
   "image": "images/roots-reptiles/snapping-turtle-1.jpg",
   "credit": "Photo: wrdrmay, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/80266355",
   "alt": "Photo of a reptile"
  },
  {
   "id": "snapping-turtle",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Snapping turtle",
   "image": "images/roots-reptiles/snapping-turtle-2.jpg",
   "credit": "Photo: taylordeckard, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/219181991",
   "alt": "Photo of a reptile"
  },
  {
   "id": "snapping-turtle",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Snapping turtle",
   "image": "images/roots-reptiles/snapping-turtle-3.jpg",
   "credit": "Photo: Jerry Reynolds, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/13434091",
   "alt": "Photo of a reptile"
  },
  {
   "id": "painted-turtle",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Painted turtle",
   "image": "images/roots-reptiles/painted-turtle-1.jpg",
   "credit": "Photo: Suzanne Cadwell, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/29654607",
   "alt": "Photo of a reptile"
  },
  {
   "id": "painted-turtle",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Painted turtle",
   "image": "images/roots-reptiles/painted-turtle-2.jpg",
   "credit": "Photo: smmcdonald, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/31701224",
   "alt": "Photo of a reptile"
  },
  {
   "id": "painted-turtle",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Painted turtle",
   "image": "images/roots-reptiles/painted-turtle-3.jpg",
   "credit": "Photo: frankyj, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/207083080",
   "alt": "Photo of a reptile"
  },
  {
   "id": "spotted-turtle",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Spotted turtle",
   "image": "images/roots-reptiles/spotted-turtle-1.jpg",
   "credit": "Photo: Amy Padgett, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/269652582",
   "alt": "Photo of a reptile"
  },
  {
   "id": "spotted-turtle",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Spotted turtle",
   "image": "images/roots-reptiles/spotted-turtle-2.jpg",
   "credit": "Photo: smmcdonald, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/34991135",
   "alt": "Photo of a reptile"
  },
  {
   "id": "spotted-turtle",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Spotted turtle",
   "image": "images/roots-reptiles/spotted-turtle-3.jpg",
   "credit": "Photo: Stella Tea, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/247018694",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-box-turtle",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern box turtle",
   "image": "images/roots-reptiles/eastern-box-turtle-1.jpg",
   "credit": "Photo: emilynne, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/288762913",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-box-turtle",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern box turtle",
   "image": "images/roots-reptiles/eastern-box-turtle-2.jpg",
   "credit": "Photo: Joshua Liverman, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/35393072",
   "alt": "Photo of a reptile"
  },
  {
   "id": "eastern-box-turtle",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Eastern box turtle",
   "image": "images/roots-reptiles/eastern-box-turtle-3.jpg",
   "credit": "Photo: funnystuff2495, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/165953413",
   "alt": "Photo of a reptile"
  },
  {
   "id": "yellow-bellied-slider",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Yellow-bellied slider",
   "image": "images/roots-reptiles/yellow-bellied-slider-1.jpg",
   "credit": "Photo: Joshua Liverman, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/42173635",
   "alt": "Photo of a reptile"
  },
  {
   "id": "yellow-bellied-slider",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Yellow-bellied slider",
   "image": "images/roots-reptiles/yellow-bellied-slider-2.jpg",
   "credit": "Photo: Beren Erkan (herper/photographer), CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/285499274",
   "alt": "Photo of a reptile"
  },
  {
   "id": "yellow-bellied-slider",
   "event": "roots-reptiles",
   "group": "reptile",
   "name": "Yellow-bellied slider",
   "image": "images/roots-reptiles/yellow-bellied-slider-3.jpg",
   "credit": "Photo: Aaron P., CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/400896833",
   "alt": "Photo of a reptile"
  },
  {
   "id": "american-toad",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "American toad",
   "image": "images/roots-reptiles/american-toad-1.jpg",
   "credit": "Photo: amphibius, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/275221235",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "american-toad",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "American toad",
   "image": "images/roots-reptiles/american-toad-2.jpg",
   "credit": "Photo: David George, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/83208446",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "american-toad",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "American toad",
   "image": "images/roots-reptiles/american-toad-3.jpg",
   "credit": "Photo: jlemmonds, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/257498568",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "pine-barrens-treefrog",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Pine Barrens treefrog",
   "image": "images/roots-reptiles/pine-barrens-treefrog-1.jpg",
   "credit": "Photo: Kevin, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/278804432",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "pine-barrens-treefrog",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Pine Barrens treefrog",
   "image": "images/roots-reptiles/pine-barrens-treefrog-2.jpg",
   "credit": "Photo: Amiel Hopkins, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/339242175",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "pine-barrens-treefrog",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Pine Barrens treefrog",
   "image": "images/roots-reptiles/pine-barrens-treefrog-3.jpg",
   "credit": "Photo: Matthew Lumsden, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/285726855",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "bullfrog",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Bullfrog",
   "image": "images/roots-reptiles/bullfrog-1.jpg",
   "credit": "Photo: Rene Kimray, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/288685409",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "bullfrog",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Bullfrog",
   "image": "images/roots-reptiles/bullfrog-2.jpg",
   "credit": "Photo: Michael J. Papay, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/230327627",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "bullfrog",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Bullfrog",
   "image": "images/roots-reptiles/bullfrog-3.jpg",
   "credit": "Photo: D. Ratchford, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/110138626",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "southern-leopard-frog",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Southern leopard frog",
   "image": "images/roots-reptiles/southern-leopard-frog-1.jpg",
   "credit": "Photo: John G. Phillips, CC BY, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/17956358",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "southern-leopard-frog",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Southern leopard frog",
   "image": "images/roots-reptiles/southern-leopard-frog-2.jpg",
   "credit": "Photo: batrachosepsdiabolicus, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/293933661",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "southern-leopard-frog",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Southern leopard frog",
   "image": "images/roots-reptiles/southern-leopard-frog-3.jpg",
   "credit": "Photo: Amy Padgett, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/166331544",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "marbled-salamander",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Marbled salamander",
   "image": "images/roots-reptiles/marbled-salamander-1.jpg",
   "credit": "Photo: Robby Deans, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/2501212",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "marbled-salamander",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Marbled salamander",
   "image": "images/roots-reptiles/marbled-salamander-2.jpg",
   "credit": "Photo: Zane Fish, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/197645264",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "marbled-salamander",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Marbled salamander",
   "image": "images/roots-reptiles/marbled-salamander-3.jpg",
   "credit": "Photo: wake_nc, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/66350444",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "red-backed-salamander",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Red-backed salamander",
   "image": "images/roots-reptiles/red-backed-salamander-1.jpg",
   "credit": "Photo: Shreybae, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/261210292",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "red-backed-salamander",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Red-backed salamander",
   "image": "images/roots-reptiles/red-backed-salamander-2.jpg",
   "credit": "Photo: Robby Deans, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/109979721",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "red-backed-salamander",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "Red-backed salamander",
   "image": "images/roots-reptiles/red-backed-salamander-3.jpg",
   "credit": "Photo: Cody Porter, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/53752859",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "white-spotted-slimy-salamander",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "White-spotted slimy salamander",
   "image": "images/roots-reptiles/white-spotted-slimy-salamander-1.jpg",
   "credit": "Photo: Kevin Metcalf, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/146923002",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "white-spotted-slimy-salamander",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "White-spotted slimy salamander",
   "image": "images/roots-reptiles/white-spotted-slimy-salamander-2.jpg",
   "credit": "Photo: randolph_nc, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/65540460",
   "alt": "Photo of an amphibian"
  },
  {
   "id": "white-spotted-slimy-salamander",
   "event": "roots-reptiles",
   "group": "amphibian",
   "name": "White-spotted slimy salamander",
   "image": "images/roots-reptiles/white-spotted-slimy-salamander-3.jpg",
   "credit": "Photo: venix, CC BY-NC, via iNaturalist",
   "source": "https://www.inaturalist.org/observations/146272327",
   "alt": "Photo of an amphibian"
  }
 ]
};
