/* Solar System question bank. Format notes are in rocks-minerals.js. */
(window.QUIZ_EVENTS = window.QUIZ_EVENTS || []).push({
  id: "solar-system",
  name: "Solar System",
  icon: "🪐",
  color: "#6a5ae0",
  blurb: "The Sun, planets, moons, dwarf planets, comets, and space missions.",
  questions: [
    // --- The Sun ---
    { q: "What is the Sun?", a: "A star", wrong: ["A planet", "A moon", "A comet"], why: "The Sun is a star, a giant ball of hot glowing gas. It's the closest star to Earth." },
    { q: "What is the Sun mostly made of?", a: "Hydrogen and helium", wrong: ["Rock and iron", "Fire and wood", "Water and ice"], why: "The Sun is about 3/4 hydrogen and 1/4 helium." },
    { q: "Deep inside the Sun, hydrogen is squeezed together to make helium. This process is called nuclear...", type: "type", a: ["fusion"], why: "Nuclear fusion releases huge amounts of energy, which is why the Sun shines." },
    { q: "About how long does sunlight take to reach Earth?", a: "About 8 minutes", wrong: ["About 1 second", "About 8 days", "About 1 year"], why: "Light is super fast, but the Sun is about 93 million miles away, so it takes about 8 minutes." },
    { q: "About how far is Earth from the Sun?", a: "93 million miles", wrong: ["93 thousand miles", "9 million miles", "93 billion miles"], why: "That distance is called 1 Astronomical Unit (AU)." },
    { q: "The average distance from Earth to the Sun is called one ___ Unit.", type: "type", a: ["astronomical", "astronomical unit", "au"], why: "1 AU is about 93 million miles. Astronomers use it to measure distances in the solar system." },
    { q: "Dark, cooler patches on the Sun's surface are called...", type: "type", a: ["sunspots", "sunspot"], why: "Sunspots look dark because they're cooler than the gas around them. They're still extremely hot!" },
    { q: "Sudden, powerful bursts of energy from the Sun's surface are called solar...", a: "Flares", wrong: ["Rings", "Tails", "Craters"], why: "Solar flares can disturb radios and satellites here on Earth." },
    { q: "The stream of charged particles flowing out from the Sun is called the solar...", type: "type", a: ["wind"], why: "When the solar wind hits Earth's magnetic field near the poles, it can make auroras." },
    { q: "The colorful lights in the sky near the North and South Poles are called...", a: "Auroras", wrong: ["Comets", "Eclipses", "Meteors"], why: "Auroras (northern and southern lights) happen when particles from the Sun hit gases high in our atmosphere." },
    { q: "About how many Earths could fit inside the Sun?", a: "About 1 million", wrong: ["About 10", "About 1,000", "About 100"], why: "The Sun is enormous: about 109 Earths wide and about 1.3 million Earths by volume." },
    { q: "True or false: The Sun is the biggest star in the universe.", a: "False", wrong: ["True"], why: "The Sun is a medium-sized star. Some stars are hundreds of times wider." },
    { q: "What holds the planets in their orbits around the Sun?", a: "Gravity", wrong: ["Magnetism", "Wind", "Sunlight"], why: "The Sun's gravity pulls on the planets and keeps them circling around it." },

    // --- Planet order and groups ---
    { q: "Which planet is closest to the Sun?", a: "Mercury", wrong: ["Venus", "Earth", "Mars"], why: "The order is Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune." },
    { q: "Which planet is farthest from the Sun?", a: "Neptune", wrong: ["Uranus", "Saturn", "Pluto"], why: "Neptune is the eighth and farthest planet. Pluto is now called a dwarf planet." },
    { q: "How many planets are in our solar system?", a: "8", wrong: ["7", "9", "10"], why: "There are 8 planets. Pluto was reclassified as a dwarf planet in 2006." },
    { q: "Which planet is third from the Sun?", type: "type", a: ["earth"], why: "Mercury, Venus, then Earth, our home!" },
    { q: "Which planet comes right after Earth, going outward from the Sun?", a: "Mars", wrong: ["Venus", "Jupiter", "Saturn"], why: "Earth is third, Mars is fourth." },
    { q: "Which planet is between Saturn and Neptune?", a: "Uranus", wrong: ["Jupiter", "Mars", "Pluto"], why: "Order: Jupiter, Saturn, Uranus, Neptune." },
    { q: "What do the first letters of 'My Very Educated Mother Just Served Us Noodles' help you remember?", a: "The order of the planets", wrong: ["The colors of the rainbow", "The phases of the Moon", "The layers of the Sun"], why: "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune." },
    { q: "Which planets are the four rocky 'inner' or 'terrestrial' planets?", a: "Mercury, Venus, Earth, Mars", wrong: ["Jupiter, Saturn, Uranus, Neptune", "Earth, Mars, Jupiter, Saturn", "Mercury, Earth, Saturn, Pluto"], why: "Terrestrial planets have solid, rocky surfaces, like Earth." },
    { q: "Jupiter, Saturn, Uranus, and Neptune are giant planets without a solid surface to stand on. They're sometimes called...", a: "Gas giants", wrong: ["Rocky planets", "Dwarf planets", "Moons"], why: "Jupiter and Saturn are gas giants. Uranus and Neptune are often called ice giants." },
    { q: "Uranus and Neptune are sometimes called ice giants. What does 'ice' mean here?", a: "Water, ammonia, and methane", wrong: ["Frozen oceans on the surface", "Snowmen", "Glaciers like on Earth"], why: "To astronomers, 'ices' are materials like water, ammonia, and methane, which make up much of these planets." },
    { q: "What separates the inner rocky planets from the outer giant planets?", a: "The asteroid belt", wrong: ["The Kuiper Belt", "The Moon", "The Oort Cloud"], why: "The main asteroid belt lies between Mars and Jupiter." },
    { q: "Which planet is the largest in our solar system?", a: "Jupiter", wrong: ["Saturn", "Earth", "Neptune"], why: "Jupiter is so big that all the other planets could fit inside it." },
    { q: "Which planet is the smallest in our solar system?", a: "Mercury", wrong: ["Mars", "Venus", "Pluto"], why: "Mercury is only a little bigger than Earth's Moon. (Pluto is smaller, but it's a dwarf planet.)" },
    { q: "Which planet is the hottest?", a: "Venus", wrong: ["Mercury", "Mars", "Jupiter"], hint: "It's not the closest one!", why: "Venus's thick carbon dioxide air traps heat like a blanket, so it's hotter than Mercury, even though Mercury is closer." },
    { q: "Why is Venus hotter than Mercury?", a: "Its thick atmosphere traps heat", wrong: ["It is closer to the Sun", "It has volcanoes erupting everywhere", "It spins faster"], why: "This is called a runaway greenhouse effect. Venus's surface is hot enough to melt lead." },

    // --- Mercury & Venus ---
    { q: "Which planet has the shortest year, going around the Sun in only 88 days?", a: "Mercury", wrong: ["Venus", "Mars", "Earth"], why: "Mercury is closest to the Sun, so it has the shortest trip around it." },
    { q: "Mercury's surface is covered with craters and looks a lot like...", a: "Earth's Moon", wrong: ["Jupiter's clouds", "Earth's oceans", "Saturn's rings"], why: "Mercury has almost no atmosphere to protect it, so space rocks leave lots of craters." },
    { q: "Which planet is sometimes called Earth's 'sister' or 'twin' because it's about the same size?", a: "Venus", wrong: ["Mars", "Mercury", "Neptune"], why: "Venus is close to Earth's size, but it's a scorching, cloudy place." },
    { q: "Venus spins in the opposite direction from most planets. On Venus, the Sun rises in the...", a: "West", wrong: ["East", "North", "South"], why: "Venus rotates backward, so its sunrise is in the west." },
    { q: "Which planet has a day that is longer than its year?", a: "Venus", wrong: ["Earth", "Jupiter", "Mars"], why: "Venus spins so slowly that one full spin (243 Earth days) takes longer than one trip around the Sun (225 days)." },
    { q: "Venus's thick clouds are made of...", a: "Sulfuric acid", wrong: ["Water vapor", "Dust", "Ice cream"], why: "Venus's clouds are made of sulfuric acid, and its air is mostly carbon dioxide." },
    { q: "Besides the Moon, which planet is the brightest object in Earth's night sky?", a: "Venus", wrong: ["Mars", "Jupiter", "Saturn"], why: "Venus's bright clouds reflect lots of sunlight. People call it the 'morning star' or 'evening star.'" },
    { q: "Which two planets have NO moons?", a: "Mercury and Venus", wrong: ["Earth and Mars", "Uranus and Neptune", "Mars and Jupiter"], why: "Mercury and Venus are the only planets without any moons." },

    // --- Earth & Moon ---
    { q: "About how long does it take Earth to go around the Sun once?", a: "365 days", wrong: ["24 hours", "30 days", "7 days"], why: "One trip around the Sun is one year: about 365 1/4 days. That extra quarter day is why we have leap years." },
    { q: "About how long does it take Earth to spin around once on its axis?", a: "24 hours", wrong: ["365 days", "1 hour", "7 days"], why: "One spin is one day. That spin gives us day and night." },
    { q: "What causes day and night on Earth?", a: "Earth spinning on its axis", wrong: ["Earth going around the Sun", "The Moon blocking the Sun", "Clouds covering the Sun"], why: "When your side of Earth faces the Sun, it's day. When it turns away, it's night." },
    { q: "What causes the seasons on Earth?", a: "The tilt of Earth's axis", wrong: ["Earth getting closer to and farther from the Sun", "The Moon's phases", "Sunspots"], why: "Earth is tilted about 23.5 degrees. When your half tilts toward the Sun, sunlight hits more directly and it's summer." },
    { q: "Earth's path around the Sun is called its...", type: "type", a: ["orbit"], why: "An orbit is the curved path one object takes around another." },
    { q: "Spinning around like a top is called rotation. Traveling around the Sun is called...", a: "Revolution", wrong: ["Rotation", "Reflection", "Eclipse"], why: "Earth rotates once a day and revolves around the Sun once a year." },
    { q: "Which planet is the only one known to have liquid water oceans on its surface and life?", a: "Earth", wrong: ["Mars", "Venus", "Jupiter"], why: "Earth is at just the right distance from the Sun for liquid water. That's sometimes called the 'Goldilocks zone.'" },
    { q: "Why does the Moon shine at night?", a: "It reflects light from the Sun", wrong: ["It makes its own light", "It is on fire", "It reflects light from Earth's cities"], why: "The Moon doesn't make light. We see sunlight bouncing off its surface." },
    { q: "About how long does it take the Moon to go through all its phases?", a: "About a month (29.5 days)", wrong: ["About a week", "About a year", "About a day"], why: "From one full moon to the next is about 29.5 days. The word 'month' comes from 'moon'!" },
    { q: "When we can't see the lit part of the Moon at all, what phase is it?", a: "New moon", wrong: ["Full moon", "First quarter", "Waxing gibbous"], why: "At new moon, the lit side faces away from Earth." },
    { q: "When the lit part of the Moon is getting bigger each night, the Moon is...", a: "Waxing", wrong: ["Waning", "Eclipsing", "Orbiting"], why: "Waxing means growing. Waning means shrinking." },
    { q: "When the lit part of the Moon is getting smaller each night, the Moon is...", type: "type", a: ["waning"], why: "Waning means shrinking. After full moon, the Moon wanes back toward new moon." },
    { q: "When the Moon is more than half lit but not full, it's called...", a: "Gibbous", wrong: ["Crescent", "New", "Quarter"], why: "Gibbous means 'hump-shaped.' Less than half lit is a crescent." },
    { q: "Why do we always see the same side of the Moon from Earth?", a: "The Moon spins once for each trip around Earth", wrong: ["The Moon doesn't spin at all", "The other side is always dark", "Earth blocks the other side"], why: "This is called tidal locking. The Moon's day matches its orbit, so the same face points at us." },
    { q: "When the Moon passes between the Sun and Earth and blocks the Sun, it's a...", a: "Solar eclipse", wrong: ["Lunar eclipse", "New star", "Meteor shower"], why: "In a solar eclipse the Moon's shadow falls on Earth. Never look at the Sun without proper eclipse glasses!" },
    { q: "When Earth's shadow falls on the Moon, it's a...", a: "Lunar eclipse", wrong: ["Solar eclipse", "Supernova", "Sunspot"], why: "During a total lunar eclipse, the Moon often turns a reddish color, sometimes called a 'blood moon.'" },
    { q: "What mostly causes ocean tides on Earth?", a: "The Moon's gravity", wrong: ["Wind", "Earthquakes", "Fish swimming"], why: "The Moon's gravity pulls on Earth's oceans. The Sun helps a little too." },
    { q: "The dark, flat areas on the Moon made of old lava are called 'maria.' What does 'maria' mean in Latin?", a: "Seas", wrong: ["Mountains", "Craters", "Holes"], why: "Early astronomers thought the dark areas were seas of water. They're really old lava plains." },
    { q: "What are the bowl-shaped holes on the Moon made by space rocks crashing into it?", type: "type", a: ["craters", "crater", "impact craters"], why: "The Moon has no air or weather, so craters can last for billions of years." },
    { q: "Who was the first person to walk on the Moon?", a: "Neil Armstrong", wrong: ["Buzz Aldrin", "John Glenn", "Sally Ride"], why: "Neil Armstrong stepped onto the Moon on July 20, 1969, during Apollo 11. Buzz Aldrin followed him." },
    { q: "Which space program landed astronauts on the Moon?", a: "Apollo", wrong: ["Voyager", "Hubble", "Mariner"], why: "Apollo 11 made the first landing in 1969. Twelve astronauts walked on the Moon in all." },

    // --- Mars ---
    { q: "Which planet is called the Red Planet?", type: "type", a: ["mars"], why: "Mars looks red because its dusty soil has lots of iron oxide, which is rust!" },
    { q: "Why is Mars red?", a: "Its dirt contains rusty iron", wrong: ["It is very hot", "It is covered in red plants", "Its sky reflects red light from the Sun"], why: "Iron in Mars's soil has rusted, turning the whole planet reddish." },
    { q: "Olympus Mons, the biggest volcano in the solar system, is on which planet?", a: "Mars", wrong: ["Earth", "Venus", "Jupiter"], why: "Olympus Mons is about 2 1/2 times taller than Mount Everest." },
    { q: "What are the names of Mars's two small moons?", a: "Phobos and Deimos", wrong: ["Io and Europa", "Titan and Enceladus", "Luna and Sol"], why: "Their names mean 'fear' and 'dread' in Greek, the companions of the war god Mars." },
    { q: "What are robot vehicles that drive around on Mars exploring called?", type: "type", a: ["rovers", "rover", "mars rovers"], why: "Rovers like Curiosity and Perseverance explore Mars and send pictures and science back to Earth." },
    { q: "Which NASA rover landed on Mars in 2021 and brought a small helicopter named Ingenuity?", a: "Perseverance", wrong: ["Sojourner", "Voyager", "Hubble"], why: "Ingenuity became the first aircraft to fly on another planet." },
    { q: "Valles Marineris on Mars is a giant...", a: "Canyon", wrong: ["Volcano", "Ocean", "Moon"], why: "Valles Marineris is far longer and deeper than the Grand Canyon." },
    { q: "Mars has white polar ice caps made of water ice and frozen...", a: "Carbon dioxide", wrong: ["Milk", "Oxygen", "Salt"], why: "Frozen carbon dioxide is also called dry ice." },

    // --- Jupiter ---
    { q: "Jupiter's Great Red Spot is a giant...", a: "Storm", wrong: ["Volcano", "Ocean", "Crater"], why: "It's a storm bigger than Earth that has been spinning for hundreds of years." },
    { q: "Which planet has the shortest day, spinning once in about 10 hours?", a: "Jupiter", wrong: ["Earth", "Mercury", "Venus"], why: "Even though it's the biggest planet, Jupiter spins the fastest." },
    { q: "Jupiter's four biggest moons were discovered in 1610 by which scientist?", a: "Galileo", wrong: ["Isaac Newton", "Albert Einstein", "Neil Armstrong"], why: "They're called the Galilean moons: Io, Europa, Ganymede, and Callisto." },
    { q: "What is the largest moon in the solar system?", a: "Ganymede", wrong: ["Titan", "Earth's Moon", "Europa"], why: "Jupiter's moon Ganymede is even bigger than the planet Mercury!" },
    { q: "Which moon of Jupiter has the most active volcanoes in the solar system?", a: "Io", wrong: ["Europa", "Titan", "Phobos"], why: "Jupiter's gravity squeezes Io so much that it heats up inside and erupts constantly." },
    { q: "Which moon of Jupiter has an icy crust with a salty ocean hidden underneath?", a: "Europa", wrong: ["Io", "Phobos", "Triton"], why: "Scientists think Europa's hidden ocean might be a place where life could exist." },
    { q: "True or false: Jupiter has rings.", a: "True", wrong: ["False"], why: "Jupiter has faint, thin rings made of dust. All four giant planets have rings!" },
    { q: "Which NASA spacecraft arrived at Jupiter in 2016 to study it up close?", a: "Juno", wrong: ["Apollo", "Viking", "Sojourner"], why: "Juno studies Jupiter's clouds, gravity, and magnetic field." },

    // --- Saturn ---
    { q: "Which planet is most famous for its big, bright rings?", type: "type", a: ["saturn"], why: "All the giant planets have rings, but Saturn's are the biggest and brightest." },
    { q: "Saturn's rings are made mostly of...", a: "Chunks of ice and rock", wrong: ["Solid gold", "Gas", "One solid sheet of metal"], why: "The rings are billions of pieces, from specks of dust to chunks as big as houses, mostly water ice." },
    { q: "Which planet is less dense than water, so it would float in a giant bathtub?", a: "Saturn", wrong: ["Jupiter", "Earth", "Mars"], why: "Saturn is mostly light gases, so it's less dense than water." },
    { q: "Saturn's biggest moon, which has a thick hazy atmosphere and lakes of liquid methane, is...", a: "Titan", wrong: ["Ganymede", "Io", "Triton"], why: "Titan is the only moon with a thick atmosphere, and it has rain, rivers, and lakes of methane." },
    { q: "Which icy moon of Saturn shoots geysers of water out into space?", a: "Enceladus", wrong: ["Titan", "Io", "Phobos"], why: "The Cassini spacecraft flew through Enceladus's geysers and found an ocean hidden under the ice." },
    { q: "Which spacecraft orbited Saturn for 13 years before diving into the planet in 2017?", a: "Cassini", wrong: ["Juno", "Curiosity", "Apollo 11"], why: "Cassini taught us about Saturn's rings and moons, and dropped the Huygens probe onto Titan." },
    { q: "Saturn has a six-sided cloud pattern at its north pole shaped like a...", a: "Hexagon", wrong: ["Circle", "Triangle", "Star"], why: "Saturn's hexagon is a jet stream wider than Earth." },

    // --- Uranus & Neptune ---
    { q: "Which planet spins on its side, like a rolling ball?", a: "Uranus", wrong: ["Neptune", "Saturn", "Mars"], why: "Uranus is tipped over about 98 degrees. Scientists think something huge crashed into it long ago." },
    { q: "Uranus and Neptune look blue because their atmospheres contain...", a: "Methane", wrong: ["Water", "Oxygen", "Blue paint"], why: "Methane gas absorbs red light and reflects blue light." },
    { q: "Which planet was the first to be discovered with a telescope, by William Herschel in 1781?", a: "Uranus", wrong: ["Neptune", "Saturn", "Mars"], why: "Mercury through Saturn can be seen without a telescope. Uranus was found by telescope." },
    { q: "Which planet was found using math before anyone saw it through a telescope?", a: "Neptune", wrong: ["Uranus", "Mars", "Jupiter"], why: "Astronomers noticed Uranus being tugged by something and calculated where Neptune had to be." },
    { q: "Which planet has the fastest winds in the solar system?", a: "Neptune", wrong: ["Earth", "Mercury", "Mars"], why: "Neptune's winds can blow over 1,200 miles per hour!" },
    { q: "Neptune's largest moon orbits backward and has geysers of nitrogen. What is it called?", a: "Triton", wrong: ["Titan", "Io", "Phobos"], why: "Triton orbits opposite to Neptune's spin, so it may be a captured Kuiper Belt object." },
    { q: "Which is the only spacecraft to fly past Uranus and Neptune?", a: "Voyager 2", wrong: ["Apollo 11", "Hubble", "Perseverance"], why: "Voyager 2 flew by Uranus in 1986 and Neptune in 1989." },
    { q: "Which planet takes the longest to go around the Sun, about 165 Earth years?", a: "Neptune", wrong: ["Uranus", "Saturn", "Jupiter"], why: "Farther planets travel a much bigger circle, and they move more slowly." },

    // --- Dwarf planets and small bodies ---
    { q: "In 2006, Pluto was reclassified as a...", a: "Dwarf planet", wrong: ["Moon", "Comet", "Star"], why: "Pluto is round and orbits the Sun, but it hasn't cleared other objects out of its path." },
    { q: "What is the largest object in the asteroid belt, a dwarf planet?", a: "Ceres", wrong: ["Pluto", "Eris", "Vesta"], why: "Ceres is the only dwarf planet in the inner solar system." },
    { q: "Which spacecraft flew past Pluto in 2015 and took the first close-up pictures?", a: "New Horizons", wrong: ["Voyager 1", "Cassini", "Juno"], why: "New Horizons found a heart-shaped plain of ice on Pluto!" },
    { q: "What is Pluto's largest moon, which is about half Pluto's size?", a: "Charon", wrong: ["Titan", "Triton", "Phobos"], why: "Pluto and Charon are so close in size that they orbit a point between them." },
    { q: "The icy region beyond Neptune where Pluto lives is called the ___ Belt.", type: "type", a: ["kuiper"], hint: "It rhymes with 'viper.'", why: "The Kuiper Belt is full of icy objects, including dwarf planets like Pluto." },
    { q: "Rocky objects that orbit the Sun, mostly between Mars and Jupiter, are called...", type: "type", a: ["asteroids", "asteroid"], why: "Most asteroids are in the main asteroid belt." },
    { q: "An icy 'dirty snowball' that grows a glowing tail when it gets near the Sun is a...", type: "type", a: ["comet"], why: "The Sun's heat turns a comet's ice to gas, making a fuzzy head and a long tail." },
    { q: "Which way does a comet's tail point?", a: "Away from the Sun", wrong: ["Toward the Sun", "Always behind the comet", "Toward Earth"], why: "The solar wind and sunlight push the tail away from the Sun, even when the comet is heading outward." },
    { q: "Which famous comet returns about every 76 years?", a: "Halley's Comet", wrong: ["Comet Pluto", "The North Star", "Comet Cassini"], why: "Halley's Comet was last seen in 1986 and will be back around 2061." },
    { q: "A space rock that burns up in Earth's atmosphere, making a streak of light, is a...", a: "Meteor", wrong: ["Meteorite", "Comet", "Star"], why: "People call meteors 'shooting stars,' but they aren't stars at all." },
    { q: "A space rock that survives its fall and lands on Earth's surface is called a...", type: "type", a: ["meteorite"], why: "Meteoroid in space, meteor in the sky, meteorite on the ground." },
    { q: "A small rock traveling through space, before it enters any atmosphere, is called a...", a: "Meteoroid", wrong: ["Meteorite", "Meteor", "Moon"], why: "Meteoroid (in space), meteor (streak in sky), meteorite (on the ground)." },
    { q: "The far-away shell of icy objects surrounding our whole solar system is called the ___ Cloud.", a: "Oort", wrong: ["Kuiper", "Milky", "Solar"], why: "Many long-period comets are thought to come from the Oort Cloud." },

    // --- Missions & big picture ---
    { q: "Which spacecraft is the farthest human-made object from Earth, now in interstellar space?", a: "Voyager 1", wrong: ["Apollo 11", "Hubble", "Curiosity"], why: "Voyager 1 launched in 1977 and crossed into interstellar space in 2012." },
    { q: "Which giant space telescope, launched in 2021, sees in infrared light?", a: "James Webb Space Telescope", wrong: ["Hubble Space Telescope", "Voyager 2", "Galileo"], why: "The James Webb Space Telescope has a huge gold-coated mirror." },
    { q: "What is the name of our galaxy?", a: "The Milky Way", wrong: ["Andromeda", "The Kuiper Belt", "The Big Dipper"], why: "Our solar system is one small part of the Milky Way galaxy, which has billions of stars." },
    { q: "The idea that the Sun, not Earth, is at the center of the solar system was proposed by...", a: "Nicolaus Copernicus", wrong: ["Neil Armstrong", "Isaac Newton", "Albert Einstein"], why: "Copernicus published his Sun-centered model in 1543." },
    { q: "A scientist who studies stars, planets, and space is called an...", type: "type", a: ["astronomer", "astrophysicist"], why: "Astronomers use telescopes and spacecraft to learn about the universe." },
    { q: "The path of a planet around the Sun is not a perfect circle. It's a slightly stretched circle called an...", a: "Ellipse", wrong: ["Square", "Triangle", "Spiral"], why: "Johannes Kepler figured out that planets move in ellipses." },
    { q: "True or false: You would weigh less on the Moon than on Earth.", a: "True", wrong: ["False"], why: "The Moon's gravity is about 1/6 of Earth's, so you'd weigh about 1/6 as much." },
    { q: "How did the solar system form, according to scientists?", a: "From a spinning cloud of gas and dust", wrong: ["From a giant explosion of the Moon", "From Jupiter breaking apart", "It has always looked the same"], why: "About 4.6 billion years ago, a cloud called a nebula collapsed. The Sun formed in the middle and planets formed from the leftover disk." }
  ]
});
