/* Weather (Meteorology) question bank. Format notes are in rocks-minerals.js. */
(window.QUIZ_EVENTS = window.QUIZ_EVENTS || []).push({
  id: "weather",
  name: "Weather",
  icon: "⛈️",
  color: "#2a9bc9",
  blurb: "Clouds, the water cycle, air pressure, storms, and weather tools.",
  questions: [
    // --- Atmosphere ---
    { q: "The blanket of air that surrounds Earth is called the...", type: "type", a: ["atmosphere"], why: "The atmosphere gives us air to breathe and protects us from the Sun's harmful rays." },
    { q: "Which gas makes up most of the air we breathe?", a: "Nitrogen", wrong: ["Oxygen", "Carbon dioxide", "Helium"], why: "Air is about 78% nitrogen and 21% oxygen." },
    { q: "About how much of the air is oxygen?", a: "About 21%", wrong: ["About 78%", "About 50%", "About 1%"], why: "Nitrogen is about 78%, oxygen about 21%, and other gases make up the last 1%." },
    { q: "Which layer of the atmosphere is closest to the ground, where almost all weather happens?", a: "Troposphere", wrong: ["Stratosphere", "Mesosphere", "Thermosphere"], why: "'Tropo' means turning or changing, and the weather is always changing there." },
    { q: "Which layer of the atmosphere contains the ozone layer?", a: "Stratosphere", wrong: ["Troposphere", "Mesosphere", "Exosphere"], why: "The ozone layer absorbs harmful ultraviolet (UV) rays from the Sun." },
    { q: "What does the ozone layer protect us from?", a: "Harmful ultraviolet (UV) rays", wrong: ["Rain", "Meteorites", "Wind"], why: "UV rays can cause sunburns. Ozone absorbs most of them before they reach us." },
    { q: "In which layer of the atmosphere do most meteors burn up?", a: "Mesosphere", wrong: ["Troposphere", "Stratosphere", "Ozone layer"], why: "The mesosphere is where 'shooting stars' flash and burn up." },
    { q: "Put the layers of the atmosphere in order, starting from the ground.", a: "Troposphere, stratosphere, mesosphere, thermosphere", wrong: ["Stratosphere, troposphere, mesosphere, thermosphere", "Thermosphere, mesosphere, stratosphere, troposphere", "Mesosphere, troposphere, thermosphere, stratosphere"], why: "A silly sentence can help: 'The Strong Man's Triceps' (Troposphere, Stratosphere, Mesosphere, Thermosphere)." },
    { q: "As you climb a tall mountain, the air usually gets...", a: "Colder and thinner", wrong: ["Warmer and thicker", "Warmer and thinner", "Exactly the same"], why: "In the troposphere, air cools as you go higher, and there's less air pressing down." },
    { q: "A scientist who studies and forecasts the weather is called a...", type: "type", a: ["meteorologist"], why: "Meteorology is the study of the atmosphere and weather, not meteors!" },
    { q: "The weather in one place averaged over many years is called...", a: "Climate", wrong: ["Weather", "Forecast", "Season"], why: "Weather is what's happening today. Climate is the usual pattern over a long time." },
    { q: "Where does almost all the energy that powers Earth's weather come from?", a: "The Sun", wrong: ["The Moon", "Volcanoes", "The ocean floor"], why: "The Sun heats Earth unevenly, which makes wind, clouds, and storms." },

    // --- Water cycle ---
    { q: "When liquid water is heated and turns into water vapor, it's called...", type: "type", a: ["evaporation"], why: "The Sun evaporates water from oceans, lakes, and puddles." },
    { q: "When water vapor cools and turns back into tiny liquid droplets, like on a cold glass, it's called...", type: "type", a: ["condensation"], why: "Clouds form by condensation too." },
    { q: "Rain, snow, sleet, and hail are all kinds of...", type: "type", a: ["precipitation"], why: "Precipitation is any water that falls from clouds to the ground." },
    { q: "When plants give off water vapor through their leaves, it's called...", a: "Transpiration", wrong: ["Condensation", "Precipitation", "Collection"], why: "A big tree can give off hundreds of liters of water in a single day." },
    { q: "What powers the water cycle?", a: "The Sun and gravity", wrong: ["The Moon and wind only", "Volcanoes", "Earthquakes"], why: "The Sun lifts water up by evaporation, and gravity brings it back down as precipitation." },
    { q: "Where is most of Earth's water found?", a: "In the oceans", wrong: ["In lakes", "In clouds", "In glaciers"], why: "About 97% of Earth's water is salty ocean water." },
    { q: "Water vapor is water in which state?", a: "Gas", wrong: ["Solid", "Liquid", "Plasma"], why: "Water vapor is invisible. The white 'steam' you see is actually tiny liquid droplets." },
    { q: "The amount of water vapor in the air is called...", type: "type", a: ["humidity"], why: "High humidity makes the air feel sticky and muggy." },
    { q: "The temperature at which air gets cool enough for water vapor to condense into dew is the...", a: "Dew point", wrong: ["Boiling point", "Freezing point", "Melting point"], why: "When the temperature drops to the dew point, dew, fog, or clouds can form." },
    { q: "Tiny drops of water that form on grass on cool mornings are called...", type: "type", a: ["dew"], why: "Dew forms when the ground cools overnight and water vapor condenses on it." },
    { q: "When dew forms but it's below freezing, you get...", a: "Frost", wrong: ["Hail", "Fog", "Sleet"], why: "Frost is water vapor turning straight into ice crystals on cold surfaces." },
    { q: "Fog is really...", a: "A cloud touching the ground", wrong: ["Smoke from fires", "Dust in the air", "Frozen rain"], why: "Fog forms the same way clouds do, but right at ground level." },

    // --- Clouds ---
    { q: "Clouds are made of...", a: "Tiny water droplets or ice crystals", wrong: ["Cotton", "Smoke", "Water vapor you can't see"], why: "Each cloud droplet is so small that millions of them would fit in a raindrop." },
    { q: "Puffy, white, cotton-ball clouds seen on nice days are called...", a: "Cumulus", wrong: ["Stratus", "Cirrus", "Nimbus"], why: "Cumulus means 'heap' or 'pile' in Latin." },
    { q: "Thin, wispy clouds high in the sky made of ice crystals are called...", a: "Cirrus", wrong: ["Cumulus", "Stratus", "Fog"], why: "Cirrus means 'curl of hair.' They're so high up they're made of ice." },
    { q: "Flat, gray, blanket-like layers of cloud that cover the whole sky are called...", a: "Stratus", wrong: ["Cumulus", "Cirrus", "Cumulonimbus"], why: "Stratus means 'layer' or 'spread out.'" },
    { q: "Huge, tall storm clouds that bring thunder, lightning, and heavy rain are called...", a: "Cumulonimbus", wrong: ["Cirrus", "Stratus", "Altocumulus"], why: "'Nimbus' means rain cloud. Cumulonimbus clouds can tower more than 10 miles high." },
    { q: "In cloud names, what does 'nimbus' or 'nimbo' mean?", a: "Rain", wrong: ["High", "Puffy", "Snow only"], why: "Nimbostratus and cumulonimbus both bring precipitation." },
    { q: "In cloud names, what does 'alto' mean?", a: "Middle height", wrong: ["Very low", "Rainy", "Stormy"], why: "Altocumulus and altostratus are mid-level clouds." },
    { q: "A cumulonimbus cloud often spreads out at the top in a flat shape called an...", a: "Anvil", wrong: ["Umbrella", "Funnel", "Ring"], why: "The top flattens when the rising air hits the top of the troposphere." },
    { q: "Which cloud type's name means 'curl of hair'?", type: "type", a: ["cirrus"], why: "Cirrus clouds look like thin, wispy streaks of hair." },
    { q: "Which cloud type's name means 'heap' or 'pile'?", type: "type", a: ["cumulus"], why: "Cumulus clouds are piled-up, puffy clouds." },
    { q: "A gray, layered cloud that brings long, steady rain or snow is called...", a: "Nimbostratus", wrong: ["Cirrus", "Cumulus", "Cirrocumulus"], why: "Nimbostratus is a thick rain layer that can drizzle for hours." },
    { q: "The long white lines airplanes leave in the sky are called contrails. What are they made of?", a: "Ice crystals from the engines' water vapor", wrong: ["Smoke from the fuel", "Paint", "Dust"], why: "Hot, humid engine exhaust freezes in the very cold air up high." },
    { q: "Why do clouds usually look white?", a: "Their droplets scatter all colors of sunlight", wrong: ["They are made of snow", "They are painted by the Sun", "They reflect the ground"], why: "When clouds get very thick, less light gets through, so they look gray." },

    // --- Precipitation types ---
    { q: "Balls of ice that fall during strong thunderstorms are called...", type: "type", a: ["hail", "hailstones", "hailstone"], why: "Hailstones grow as strong winds toss them up and down through freezing parts of a storm cloud." },
    { q: "How do hailstones get bigger?", a: "Strong winds carry them up and down through the cloud, adding layers of ice", wrong: ["They melt and refreeze on the ground", "Snowflakes stick to them on the ground", "They grow in the ocean"], why: "Cut a big hailstone in half and you can see rings of ice, like an onion." },
    { q: "Rain that falls as liquid but freezes into ice pellets before it hits the ground is called...", a: "Sleet", wrong: ["Hail", "Snow", "Dew"], why: "Sleet bounces when it hits the ground." },
    { q: "Rain that falls as liquid but freezes the moment it touches cold surfaces is called...", a: "Freezing rain", wrong: ["Hail", "Snow", "Fog"], why: "Freezing rain coats everything in a shiny layer of ice. It's very slippery and dangerous." },
    { q: "How many sides or arms does a snowflake usually have?", a: "6", wrong: ["4", "5", "8"], why: "Water molecules link up in six-sided patterns when they freeze." },
    { q: "Very light rain with tiny drops is called...", a: "Drizzle", wrong: ["Hail", "Downpour", "Sleet"], why: "Drizzle often falls from low stratus clouds." },

    // --- Weather instruments ---
    { q: "What tool measures temperature?", type: "type", a: ["thermometer"], why: "Thermo means heat, and meter means measure." },
    { q: "What tool measures air pressure?", a: "Barometer", wrong: ["Thermometer", "Anemometer", "Rain gauge"], why: "'Baro' means weight. A barometer measures the weight of the air pressing down." },
    { q: "What tool measures wind speed?", a: "Anemometer", wrong: ["Barometer", "Hygrometer", "Wind vane"], why: "An anemometer has little cups that spin faster when the wind blows harder." },
    { q: "What tool shows which direction the wind is coming from?", a: "Wind vane (weather vane)", wrong: ["Anemometer", "Thermometer", "Barometer"], why: "A wind vane points into the wind, showing where it's blowing from." },
    { q: "What tool measures how much rain has fallen?", a: "Rain gauge", wrong: ["Barometer", "Anemometer", "Hygrometer"], why: "A rain gauge collects rain so you can measure how deep it is." },
    { q: "What tool measures humidity?", a: "Hygrometer", wrong: ["Thermometer", "Barometer", "Anemometer"], why: "'Hygro' means moisture or wet." },
    { q: "Which weather tool has spinning cups on top of a pole?", type: "type", a: ["anemometer"], why: "The faster the cups spin, the faster the wind is blowing." },
    { q: "A windsock is a cloth tube on a pole. What does it show?", a: "Wind direction and roughly how strong it is", wrong: ["Temperature", "Humidity", "How much it rained"], why: "You see windsocks at airports. The more it sticks straight out, the stronger the wind." },
    { q: "What do meteorologists use to 'see' rain and storms moving, even at night?", a: "Radar", wrong: ["Microscopes", "Thermometers", "Rain gauges"], why: "Radar sends out radio waves that bounce off raindrops, snow, and hail." },
    { q: "Balloons that carry weather instruments high into the sky are called...", a: "Weather balloons", wrong: ["Hot air balloons", "Party balloons", "Blimps"], why: "Hundreds of weather balloons are launched around the world twice every day." },
    { q: "What do weather satellites mainly do?", a: "Take pictures of clouds and storms from space", wrong: ["Make rain", "Measure earthquakes", "Stop hurricanes"], why: "Satellites help forecasters watch storms, like hurricanes, form and move." },

    // --- Air pressure, wind, fronts ---
    { q: "When air pressure is HIGH, the weather is usually...", a: "Clear and calm", wrong: ["Stormy", "Rainy", "Snowy"], why: "In high pressure, air sinks, which keeps clouds from forming." },
    { q: "When air pressure is LOW, the weather is usually...", a: "Cloudy and stormy", wrong: ["Sunny and dry", "Clear and calm", "Always hot"], why: "In low pressure, air rises, cools, and forms clouds and rain." },
    { q: "If the barometer reading is dropping fast, what weather is probably coming?", a: "A storm", wrong: ["Clear skies", "Nothing changes", "An earthquake"], why: "Falling pressure usually means a low-pressure system with clouds and storms is moving in." },
    { q: "Wind is air moving from...", a: "High pressure toward low pressure", wrong: ["Low pressure toward high pressure", "The Moon toward Earth", "Cold places only"], why: "Air rushes from where there's more of it (high pressure) to where there's less (low pressure)." },
    { q: "Warm air tends to...", a: "Rise", wrong: ["Sink", "Stay still", "Turn into water"], why: "Warm air is less dense than cold air, so it rises, like a hot air balloon." },
    { q: "Cold air tends to...", a: "Sink", wrong: ["Rise", "Evaporate", "Glow"], why: "Cold air is denser and heavier, so it sinks." },
    { q: "Where two air masses meet is called a...", type: "type", a: ["front", "weather front"], why: "Fronts often bring changes in weather, like clouds, rain, and temperature changes." },
    { q: "When a cold air mass pushes into a warm air mass, it's called a...", a: "Cold front", wrong: ["Warm front", "Stationary front", "High pressure"], why: "Cold fronts often bring quick, strong thunderstorms, then cooler weather." },
    { q: "On a weather map, a line with blue triangles shows a...", a: "Cold front", wrong: ["Warm front", "High pressure", "Rain gauge"], why: "Blue triangles point in the direction the cold front is moving." },
    { q: "On a weather map, a line with red half-circles shows a...", a: "Warm front", wrong: ["Cold front", "Tornado", "Hurricane"], why: "Warm fronts bring slow, steady rain and warmer weather." },
    { q: "On a weather map, a big blue 'H' marks an area of...", a: "High pressure", wrong: ["Hurricanes", "Hail", "Heat wave"], why: "H means high pressure, usually fair weather. L means low pressure, usually stormy." },
    { q: "A large body of air with about the same temperature and humidity throughout is called an air...", type: "type", a: ["mass"], why: "Air masses take on the conditions of where they form, like cold and dry over Canada or warm and wet over the Gulf of Mexico." },
    { q: "During the day at the beach, a cool breeze blows from the water toward land. This is called a...", a: "Sea breeze", wrong: ["Land breeze", "Tornado", "Jet stream"], why: "Land heats up faster than water. Warm air over the land rises, and cooler sea air flows in to replace it." },
    { q: "A fast river of wind high in the atmosphere that steers storms is called the...", a: "Jet stream", wrong: ["Gulf Stream", "Sea breeze", "Trade wind"], why: "Airplanes flying east can ride the jet stream to save time and fuel." },
    { q: "Winds are named for the direction they come FROM. A 'west wind' blows...", a: "From the west toward the east", wrong: ["From the east toward the west", "Straight up", "In circles"], why: "A west wind comes from the west. A wind vane points toward where the wind is coming from." },
    { q: "Earth's spin makes winds and storms curve. This is called the ___ effect.", a: "Coriolis", wrong: ["Doppler", "Greenhouse", "Domino"], why: "The Coriolis effect is why hurricanes spin counterclockwise in the Northern Hemisphere." },

    // --- Severe weather ---
    { q: "What causes thunder?", a: "Lightning heating the air so fast it expands with a boom", wrong: ["Clouds bumping into each other", "Rain hitting the ground", "Wind blowing through trees"], why: "Lightning heats air to about 50,000°F in an instant, making it explode outward." },
    { q: "Why do you see lightning before you hear thunder?", a: "Light travels much faster than sound", wrong: ["Thunder happens later", "Your ears are slow", "Lightning is closer"], why: "Count the seconds between the flash and the boom, then divide by 5 to estimate how many miles away it is." },
    { q: "You see lightning and count 10 seconds before the thunder. About how far away is the storm?", a: "About 2 miles", wrong: ["About 10 miles", "About 50 miles", "Right on top of you"], hint: "Sound travels about 1 mile every 5 seconds.", why: "Sound travels about 1 mile every 5 seconds, so 10 seconds is about 2 miles." },
    { q: "What is a good lightning safety rule?", a: "When thunder roars, go indoors", wrong: ["Stand under a tall tree", "Go swimming", "Hold up a metal pole"], why: "If you can hear thunder, you're close enough to be struck. Wait 30 minutes after the last thunder." },
    { q: "Is it safe to take shelter under a tall tree during a thunderstorm?", a: "No, lightning often strikes tall objects", wrong: ["Yes, trees block lightning", "Yes, if the tree is wet", "Only if it's an oak tree"], why: "Get inside a building or a hard-topped car instead." },
    { q: "A spinning column of air that reaches from a thunderstorm down to the ground is a...", type: "type", a: ["tornado", "twister"], why: "Tornadoes can have the fastest winds on Earth, over 200 mph." },
    { q: "Which scale rates how strong a tornado is, based on the damage it causes?", a: "Enhanced Fujita (EF) scale", wrong: ["Saffir-Simpson scale", "Richter scale", "Mohs scale"], why: "Tornadoes are rated EF0 (weakest) to EF5 (strongest)." },
    { q: "The part of the United States that gets lots of tornadoes is nicknamed...", a: "Tornado Alley", wrong: ["Hurricane Highway", "Storm Street", "Twister Town"], why: "Tornado Alley stretches across the Great Plains, from Texas up through Oklahoma, Kansas, and Nebraska." },
    { q: "What is the difference between a tornado WATCH and a tornado WARNING?", a: "A watch means tornadoes could form; a warning means one has been spotted or seen on radar", wrong: ["They mean exactly the same thing", "A watch is more dangerous", "A warning means the tornado is over"], why: "During a warning, go to a safe place right away, like a basement or an inside room with no windows." },
    { q: "A huge spinning storm that forms over warm ocean water, with winds of at least 74 mph, is a...", type: "type", a: ["hurricane", "typhoon", "cyclone", "tropical cyclone"], why: "In the Pacific they're called typhoons, and in the Indian Ocean, cyclones." },
    { q: "The calm, clear center of a hurricane is called the...", type: "type", a: ["eye"], why: "The strongest winds are in the eyewall, the ring of storms right around the eye." },
    { q: "Hurricanes get their energy from...", a: "Warm ocean water", wrong: ["Cold mountain air", "Desert sand", "Lightning"], why: "That's why hurricanes weaken once they move over land or cold water." },
    { q: "Which scale rates hurricanes from Category 1 to Category 5?", a: "Saffir-Simpson scale", wrong: ["Enhanced Fujita scale", "Richter scale", "Beaufort scale"], why: "Category 5 hurricanes have winds of 157 mph or more." },
    { q: "Ocean water pushed onto land by a hurricane's winds is called a storm...", type: "type", a: ["surge"], why: "Storm surge is often the most dangerous part of a hurricane." },
    { q: "A severe winter storm with strong winds, blowing snow, and very low visibility is a...", type: "type", a: ["blizzard"], why: "Blizzards make it very hard to see and very dangerous to travel." },
    { q: "A long time with much less rain than normal is called a...", type: "type", a: ["drought"], why: "Droughts can dry up crops, rivers, and lakes." },
    { q: "Which scale uses wind effects, like waving branches and white-capped waves, to estimate wind speed?", a: "Beaufort scale", wrong: ["Mohs scale", "Richter scale", "Fujita scale"], why: "The Beaufort scale goes from 0 (calm) to 12 (hurricane force)." },
    { q: "A rainbow appears when sunlight shines through...", a: "Raindrops", wrong: ["Snowflakes on the ground", "Dust", "Smoke"], why: "Raindrops bend and split sunlight into its colors. The Sun has to be behind you to see one." },
    { q: "What are the colors of the rainbow, in order?", a: "Red, orange, yellow, green, blue, indigo, violet", wrong: ["Red, yellow, orange, green, violet, blue, indigo", "Blue, green, red, yellow, violet, orange, indigo", "Violet, red, green, blue, orange, yellow, indigo"], why: "Remember ROY G. BIV!" },
    { q: "Why does the sky look blue on a clear day?", a: "Air scatters blue sunlight more than other colors", wrong: ["It reflects the ocean", "Air is painted blue", "Clouds are blue"], why: "Blue light bounces around the sky the most, so blue comes at us from every direction." },

    // --- Temperature and forecasting ---
    { q: "At what temperature does water freeze on the Fahrenheit scale?", a: "32°F", wrong: ["0°F", "100°F", "212°F"], why: "Water freezes at 32°F, which is the same as 0°C." },
    { q: "At what temperature does water freeze on the Celsius scale?", a: "0°C", wrong: ["32°C", "100°C", "-10°C"], why: "The Celsius scale was built around water: 0° freezing and 100° boiling." },
    { q: "What does a weather 'forecast' do?", a: "Predicts what the weather will be", wrong: ["Measures earthquakes", "Reports yesterday's weather only", "Controls the weather"], why: "Meteorologists use data and computer models to forecast the weather." },
    { q: "'Red sky at night, sailor's delight.' This old saying suggests a red sunset means...", a: "Good weather is coming", wrong: ["A storm is coming", "It will snow", "The Sun is broken"], why: "In many places, weather moves west to east, so a clear western sky at sunset often means fair weather next." },
    { q: "When it's windy and cold, how cold it feels on your skin is called the...", a: "Wind chill", wrong: ["Heat index", "Dew point", "Air mass"], why: "Wind carries heat away from your body, so you feel colder than the thermometer shows." },
    { q: "On hot, humid days, how hot it feels to your body is called the...", a: "Heat index", wrong: ["Wind chill", "Barometer", "Dew"], why: "Humid air makes it harder for sweat to evaporate and cool you off." },
    { q: "Which is usually warmer during a sunny summer afternoon: dry sand or ocean water?", a: "Dry sand", wrong: ["Ocean water", "They are always the same", "Neither gets warm"], why: "Land heats up and cools down faster than water. That's why sand can burn your feet while the water feels cool." },
    { q: "Why are places near the equator usually warmer than places near the poles?", a: "Sunlight hits the equator more directly", wrong: ["The equator is closer to the Sun", "The poles have no sunlight ever", "The equator has more volcanoes"], why: "Near the poles, sunlight comes in at a low slant and spreads out over more ground." },
    { q: "A cloud that forms a funnel shape but doesn't touch the ground is called a...", a: "Funnel cloud", wrong: ["Cirrus", "Fog bank", "Contrail"], why: "If a funnel cloud reaches the ground, it becomes a tornado." },
    { q: "A tornado that forms over water is called a...", type: "type", a: ["waterspout"], why: "Waterspouts look like spinning tubes connecting a cloud to the water." },
    { q: "About how fast does sound travel through air?", a: "About 1 mile every 5 seconds", wrong: ["About 1 mile every second", "About 1 mile every minute", "Instantly"], why: "That's roughly 760 miles per hour, fast, but nowhere near as fast as light." },
    { q: "The greenhouse effect happens when some gases in the atmosphere...", a: "Trap heat near Earth's surface", wrong: ["Make plants grow faster", "Block all sunlight", "Create rain"], why: "Gases like carbon dioxide and water vapor trap heat. Without any greenhouse effect, Earth would be frozen." }
  ]
});
